// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package nodes_get
//

// Package nodes_get is a generated GoMock package.
package nodes_get

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocknodesRepo is a mock of nodesRepo interface.
type MocknodesRepo struct {
	ctrl     *gomock.Controller
	recorder *MocknodesRepoMockRecorder
	isgomock struct{}
}

// MocknodesRepoMockRecorder is the mock recorder for MocknodesRepo.
type MocknodesRepoMockRecorder struct {
	mock *MocknodesRepo
}

// NewMocknodesRepo creates a new mock instance.
func NewMocknodesRepo(ctrl *gomock.Controller) *MocknodesRepo {
	mock := &MocknodesRepo{ctrl: ctrl}
	mock.recorder = &MocknodesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodesRepo) EXPECT() *MocknodesRepoMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MocknodesRepo) List(ctx context.Context) ([]entity.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocknodesRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocknodesRepo)(nil).List), ctx)
}
