// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package user_create
//

// Package user_create is a generated GoMock package.
package user_create

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockcreator is a mock of creator interface.
type Mockcreator struct {
	ctrl     *gomock.Controller
	recorder *MockcreatorMockRecorder
	isgomock struct{}
}

// MockcreatorMockRecorder is the mock recorder for Mockcreator.
type MockcreatorMockRecorder struct {
	mock *Mockcreator
}

// NewMockcreator creates a new mock instance.
func NewMockcreator(ctrl *gomock.Controller) *Mockcreator {
	mock := &Mockcreator{ctrl: ctrl}
	mock.recorder = &MockcreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcreator) EXPECT() *MockcreatorMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *Mockcreator) CreateUser(ctx context.Context, name string, sel entity.ConnectionSelection) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, name, sel)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockcreatorMockRecorder) CreateUser(ctx, name, sel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*Mockcreator)(nil).CreateUser), ctx, name, sel)
}
