// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package config_api
//

// Package config_api is a generated GoMock package.
package config_api

import (
	context "context"
	reflect "reflect"

	mihomo "github.com/postlog/subgen/internal/mihomo"
	gomock "go.uber.org/mock/gomock"
)

// MockmihomoReader is a mock of mihomoReader interface.
type MockmihomoReader struct {
	ctrl     *gomock.Controller
	recorder *MockmihomoReaderMockRecorder
	isgomock struct{}
}

// MockmihomoReaderMockRecorder is the mock recorder for MockmihomoReader.
type MockmihomoReaderMockRecorder struct {
	mock *MockmihomoReader
}

// NewMockmihomoReader creates a new mock instance.
func NewMockmihomoReader(ctrl *gomock.Controller) *MockmihomoReader {
	mock := &MockmihomoReader{ctrl: ctrl}
	mock.recorder = &MockmihomoReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmihomoReader) EXPECT() *MockmihomoReaderMockRecorder {
	return m.recorder
}

// ProxyGroups mocks base method.
func (m *MockmihomoReader) ProxyGroups(ctx context.Context) ([]mihomo.ProxyGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyGroups", ctx)
	ret0, _ := ret[0].([]mihomo.ProxyGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProxyGroups indicates an expected call of ProxyGroups.
func (mr *MockmihomoReaderMockRecorder) ProxyGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyGroups", reflect.TypeOf((*MockmihomoReader)(nil).ProxyGroups), ctx)
}

// RuleProviders mocks base method.
func (m *MockmihomoReader) RuleProviders(ctx context.Context) ([]mihomo.RuleProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RuleProviders", ctx)
	ret0, _ := ret[0].([]mihomo.RuleProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RuleProviders indicates an expected call of RuleProviders.
func (mr *MockmihomoReaderMockRecorder) RuleProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RuleProviders", reflect.TypeOf((*MockmihomoReader)(nil).RuleProviders), ctx)
}

// Rules mocks base method.
func (m *MockmihomoReader) Rules(ctx context.Context) ([]mihomo.RoutingRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rules", ctx)
	ret0, _ := ret[0].([]mihomo.RoutingRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rules indicates an expected call of Rules.
func (mr *MockmihomoReaderMockRecorder) Rules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rules", reflect.TypeOf((*MockmihomoReader)(nil).Rules), ctx)
}

// Setting mocks base method.
func (m *MockmihomoReader) Setting(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Setting", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Setting indicates an expected call of Setting.
func (mr *MockmihomoReaderMockRecorder) Setting(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setting", reflect.TypeOf((*MockmihomoReader)(nil).Setting), ctx, key)
}
