// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package config_api
//

// Package config_api is a generated GoMock package.
package config_api

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	mihomo "github.com/postlog/subgen/internal/mihomo"
	gomock "go.uber.org/mock/gomock"
)

// MockconfigResolver is a mock of configResolver interface.
type MockconfigResolver struct {
	ctrl     *gomock.Controller
	recorder *MockconfigResolverMockRecorder
	isgomock struct{}
}

// MockconfigResolverMockRecorder is the mock recorder for MockconfigResolver.
type MockconfigResolverMockRecorder struct {
	mock *MockconfigResolver
}

// NewMockconfigResolver creates a new mock instance.
func NewMockconfigResolver(ctrl *gomock.Controller) *MockconfigResolver {
	mock := &MockconfigResolver{ctrl: ctrl}
	mock.recorder = &MockconfigResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigResolver) EXPECT() *MockconfigResolverMockRecorder {
	return m.recorder
}

// BaseConfigID mocks base method.
func (m *MockconfigResolver) BaseConfigID(ctx context.Context, kind entity.ConfigKind) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseConfigID", ctx, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BaseConfigID indicates an expected call of BaseConfigID.
func (mr *MockconfigResolverMockRecorder) BaseConfigID(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseConfigID", reflect.TypeOf((*MockconfigResolver)(nil).BaseConfigID), ctx, kind)
}

// UserConfigID mocks base method.
func (m *MockconfigResolver) UserConfigID(ctx context.Context, userID int64, kind entity.ConfigKind) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfigID", ctx, userID, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UserConfigID indicates an expected call of UserConfigID.
func (mr *MockconfigResolverMockRecorder) UserConfigID(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfigID", reflect.TypeOf((*MockconfigResolver)(nil).UserConfigID), ctx, userID, kind)
}

// MockmihomoReader is a mock of mihomoReader interface.
type MockmihomoReader struct {
	ctrl     *gomock.Controller
	recorder *MockmihomoReaderMockRecorder
	isgomock struct{}
}

// MockmihomoReaderMockRecorder is the mock recorder for MockmihomoReader.
type MockmihomoReaderMockRecorder struct {
	mock *MockmihomoReader
}

// NewMockmihomoReader creates a new mock instance.
func NewMockmihomoReader(ctrl *gomock.Controller) *MockmihomoReader {
	mock := &MockmihomoReader{ctrl: ctrl}
	mock.recorder = &MockmihomoReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmihomoReader) EXPECT() *MockmihomoReaderMockRecorder {
	return m.recorder
}

// ProxyGroups mocks base method.
func (m *MockmihomoReader) ProxyGroups(ctx context.Context, configID int64) ([]mihomo.ProxyGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyGroups", ctx, configID)
	ret0, _ := ret[0].([]mihomo.ProxyGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProxyGroups indicates an expected call of ProxyGroups.
func (mr *MockmihomoReaderMockRecorder) ProxyGroups(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyGroups", reflect.TypeOf((*MockmihomoReader)(nil).ProxyGroups), ctx, configID)
}

// RuleProviders mocks base method.
func (m *MockmihomoReader) RuleProviders(ctx context.Context, configID int64) ([]mihomo.RuleProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RuleProviders", ctx, configID)
	ret0, _ := ret[0].([]mihomo.RuleProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RuleProviders indicates an expected call of RuleProviders.
func (mr *MockmihomoReaderMockRecorder) RuleProviders(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RuleProviders", reflect.TypeOf((*MockmihomoReader)(nil).RuleProviders), ctx, configID)
}

// Rules mocks base method.
func (m *MockmihomoReader) Rules(ctx context.Context, configID int64) ([]mihomo.RoutingRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rules", ctx, configID)
	ret0, _ := ret[0].([]mihomo.RoutingRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rules indicates an expected call of Rules.
func (mr *MockmihomoReaderMockRecorder) Rules(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rules", reflect.TypeOf((*MockmihomoReader)(nil).Rules), ctx, configID)
}

// Setting mocks base method.
func (m *MockmihomoReader) Setting(ctx context.Context, configID int64, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Setting", ctx, configID, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Setting indicates an expected call of Setting.
func (mr *MockmihomoReaderMockRecorder) Setting(ctx, configID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setting", reflect.TypeOf((*MockmihomoReader)(nil).Setting), ctx, configID, key)
}
