// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package config_customs
//

// Package config_customs is a generated GoMock package.
package config_customs

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockconfigLister is a mock of configLister interface.
type MockconfigLister struct {
	ctrl     *gomock.Controller
	recorder *MockconfigListerMockRecorder
	isgomock struct{}
}

// MockconfigListerMockRecorder is the mock recorder for MockconfigLister.
type MockconfigListerMockRecorder struct {
	mock *MockconfigLister
}

// NewMockconfigLister creates a new mock instance.
func NewMockconfigLister(ctrl *gomock.Controller) *MockconfigLister {
	mock := &MockconfigLister{ctrl: ctrl}
	mock.recorder = &MockconfigListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigLister) EXPECT() *MockconfigListerMockRecorder {
	return m.recorder
}

// UserConfigUserIDs mocks base method.
func (m *MockconfigLister) UserConfigUserIDs(ctx context.Context, kind entity.ConfigKind) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfigUserIDs", ctx, kind)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserConfigUserIDs indicates an expected call of UserConfigUserIDs.
func (mr *MockconfigListerMockRecorder) UserConfigUserIDs(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfigUserIDs", reflect.TypeOf((*MockconfigLister)(nil).UserConfigUserIDs), ctx, kind)
}

// MockuserLister is a mock of userLister interface.
type MockuserLister struct {
	ctrl     *gomock.Controller
	recorder *MockuserListerMockRecorder
	isgomock struct{}
}

// MockuserListerMockRecorder is the mock recorder for MockuserLister.
type MockuserListerMockRecorder struct {
	mock *MockuserLister
}

// NewMockuserLister creates a new mock instance.
func NewMockuserLister(ctrl *gomock.Controller) *MockuserLister {
	mock := &MockuserLister{ctrl: ctrl}
	mock.recorder = &MockuserListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserLister) EXPECT() *MockuserListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockuserLister) List(ctx context.Context) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockuserListerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockuserLister)(nil).List), ctx)
}
