// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package config_customs
//

// Package config_customs is a generated GoMock package.
package config_customs

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockconfigsRepo is a mock of configsRepo interface.
type MockconfigsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockconfigsRepoMockRecorder
	isgomock struct{}
}

// MockconfigsRepoMockRecorder is the mock recorder for MockconfigsRepo.
type MockconfigsRepoMockRecorder struct {
	mock *MockconfigsRepo
}

// NewMockconfigsRepo creates a new mock instance.
func NewMockconfigsRepo(ctrl *gomock.Controller) *MockconfigsRepo {
	mock := &MockconfigsRepo{ctrl: ctrl}
	mock.recorder = &MockconfigsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigsRepo) EXPECT() *MockconfigsRepoMockRecorder {
	return m.recorder
}

// UserConfigUserIDs mocks base method.
func (m *MockconfigsRepo) UserConfigUserIDs(ctx context.Context, kind entity.ConfigKind) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfigUserIDs", ctx, kind)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserConfigUserIDs indicates an expected call of UserConfigUserIDs.
func (mr *MockconfigsRepoMockRecorder) UserConfigUserIDs(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfigUserIDs", reflect.TypeOf((*MockconfigsRepo)(nil).UserConfigUserIDs), ctx, kind)
}

// MockusersRepo is a mock of usersRepo interface.
type MockusersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockusersRepoMockRecorder
	isgomock struct{}
}

// MockusersRepoMockRecorder is the mock recorder for MockusersRepo.
type MockusersRepoMockRecorder struct {
	mock *MockusersRepo
}

// NewMockusersRepo creates a new mock instance.
func NewMockusersRepo(ctrl *gomock.Controller) *MockusersRepo {
	mock := &MockusersRepo{ctrl: ctrl}
	mock.recorder = &MockusersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockusersRepo) EXPECT() *MockusersRepoMockRecorder {
	return m.recorder
}

// ListNames mocks base method.
func (m *MockusersRepo) ListNames(ctx context.Context) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNames", ctx)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNames indicates an expected call of ListNames.
func (mr *MockusersRepoMockRecorder) ListNames(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNames", reflect.TypeOf((*MockusersRepo)(nil).ListNames), ctx)
}
