// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package user_edit
//

// Package user_edit is a generated GoMock package.
package user_edit

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockeditor is a mock of editor interface.
type Mockeditor struct {
	ctrl     *gomock.Controller
	recorder *MockeditorMockRecorder
	isgomock struct{}
}

// MockeditorMockRecorder is the mock recorder for Mockeditor.
type MockeditorMockRecorder struct {
	mock *Mockeditor
}

// NewMockeditor creates a new mock instance.
func NewMockeditor(ctrl *gomock.Controller) *Mockeditor {
	mock := &Mockeditor{ctrl: ctrl}
	mock.recorder = &MockeditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockeditor) EXPECT() *MockeditorMockRecorder {
	return m.recorder
}

// EditUser mocks base method.
func (m *Mockeditor) EditUser(ctx context.Context, p entity.UserEditParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditUser", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditUser indicates an expected call of EditUser.
func (mr *MockeditorMockRecorder) EditUser(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditUser", reflect.TypeOf((*Mockeditor)(nil).EditUser), ctx, p)
}
