// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package provisioning
//

// Package provisioning is a generated GoMock package.
package provisioning

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepo is a mock of userRepo interface.
type MockuserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepoMockRecorder
	isgomock struct{}
}

// MockuserRepoMockRecorder is the mock recorder for MockuserRepo.
type MockuserRepoMockRecorder struct {
	mock *MockuserRepo
}

// NewMockuserRepo creates a new mock instance.
func NewMockuserRepo(ctrl *gomock.Controller) *MockuserRepo {
	mock := &MockuserRepo{ctrl: ctrl}
	mock.recorder = &MockuserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepo) EXPECT() *MockuserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockuserRepo) Create(ctx context.Context, u *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockuserRepoMockRecorder) Create(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuserRepo)(nil).Create), ctx, u)
}

// Delete mocks base method.
func (m *MockuserRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockuserRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockuserRepo)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockuserRepo) Get(ctx context.Context, id int64) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockuserRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockuserRepo)(nil).Get), ctx, id)
}

// ReplaceConnections mocks base method.
func (m *MockuserRepo) ReplaceConnections(ctx context.Context, userID int64, inboundIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceConnections", ctx, userID, inboundIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceConnections indicates an expected call of ReplaceConnections.
func (mr *MockuserRepoMockRecorder) ReplaceConnections(ctx, userID, inboundIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceConnections", reflect.TypeOf((*MockuserRepo)(nil).ReplaceConnections), ctx, userID, inboundIDs)
}

// MocknodeRepo is a mock of nodeRepo interface.
type MocknodeRepo struct {
	ctrl     *gomock.Controller
	recorder *MocknodeRepoMockRecorder
	isgomock struct{}
}

// MocknodeRepoMockRecorder is the mock recorder for MocknodeRepo.
type MocknodeRepoMockRecorder struct {
	mock *MocknodeRepo
}

// NewMocknodeRepo creates a new mock instance.
func NewMocknodeRepo(ctrl *gomock.Controller) *MocknodeRepo {
	mock := &MocknodeRepo{ctrl: ctrl}
	mock.recorder = &MocknodeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodeRepo) EXPECT() *MocknodeRepoMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MocknodeRepo) List(ctx context.Context) ([]entity.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocknodeRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocknodeRepo)(nil).List), ctx)
}

// MockpanelClient is a mock of panelClient interface.
type MockpanelClient struct {
	ctrl     *gomock.Controller
	recorder *MockpanelClientMockRecorder
	isgomock struct{}
}

// MockpanelClientMockRecorder is the mock recorder for MockpanelClient.
type MockpanelClientMockRecorder struct {
	mock *MockpanelClient
}

// NewMockpanelClient creates a new mock instance.
func NewMockpanelClient(ctrl *gomock.Controller) *MockpanelClient {
	mock := &MockpanelClient{ctrl: ctrl}
	mock.recorder = &MockpanelClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpanelClient) EXPECT() *MockpanelClientMockRecorder {
	return m.recorder
}

// AddClient mocks base method.
func (m *MockpanelClient) AddClient(ctx context.Context, t entity.PanelTarget, inboundIDs []int, cs entity.ClientSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClient", ctx, t, inboundIDs, cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddClient indicates an expected call of AddClient.
func (mr *MockpanelClientMockRecorder) AddClient(ctx, t, inboundIDs, cs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClient", reflect.TypeOf((*MockpanelClient)(nil).AddClient), ctx, t, inboundIDs, cs)
}

// DelClient mocks base method.
func (m *MockpanelClient) DelClient(ctx context.Context, t entity.PanelTarget, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelClient", ctx, t, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelClient indicates an expected call of DelClient.
func (mr *MockpanelClientMockRecorder) DelClient(ctx, t, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelClient", reflect.TypeOf((*MockpanelClient)(nil).DelClient), ctx, t, email)
}

// ListInbounds mocks base method.
func (m *MockpanelClient) ListInbounds(ctx context.Context, t entity.PanelTarget) ([]entity.PanelInbound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInbounds", ctx, t)
	ret0, _ := ret[0].([]entity.PanelInbound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInbounds indicates an expected call of ListInbounds.
func (mr *MockpanelClientMockRecorder) ListInbounds(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInbounds", reflect.TypeOf((*MockpanelClient)(nil).ListInbounds), ctx, t)
}
