// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package custom_create
//

// Package custom_create is a generated GoMock package.
package custom_create

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockconfigCreator is a mock of configCreator interface.
type MockconfigCreator struct {
	ctrl     *gomock.Controller
	recorder *MockconfigCreatorMockRecorder
	isgomock struct{}
}

// MockconfigCreatorMockRecorder is the mock recorder for MockconfigCreator.
type MockconfigCreatorMockRecorder struct {
	mock *MockconfigCreator
}

// NewMockconfigCreator creates a new mock instance.
func NewMockconfigCreator(ctrl *gomock.Controller) *MockconfigCreator {
	mock := &MockconfigCreator{ctrl: ctrl}
	mock.recorder = &MockconfigCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigCreator) EXPECT() *MockconfigCreatorMockRecorder {
	return m.recorder
}

// CreateUserConfig mocks base method.
func (m *MockconfigCreator) CreateUserConfig(ctx context.Context, userID int64, kind entity.ConfigKind) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserConfig", ctx, userID, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserConfig indicates an expected call of CreateUserConfig.
func (mr *MockconfigCreatorMockRecorder) CreateUserConfig(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserConfig", reflect.TypeOf((*MockconfigCreator)(nil).CreateUserConfig), ctx, userID, kind)
}
