// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ConfigCustoms implements configCustoms operation.
	//
	// Custom-config owners + the full user list.
	//
	// GET /admin/api/config/mihomo/customs
	ConfigCustoms(ctx context.Context) (ConfigCustomsRes, error)
	// ConfigGet implements configGet operation.
	//
	// Read the mihomo config (base or a user's custom).
	//
	// GET /admin/api/config/mihomo
	ConfigGet(ctx context.Context, params ConfigGetParams) (ConfigGetRes, error)
	// ConfigSave implements configSave operation.
	//
	// Save the mihomo config.
	//
	// POST /admin/api/config/mihomo/save
	ConfigSave(ctx context.Context, req *ConfigSaveReq) (ConfigSaveRes, error)
	// ConfigSchema implements configSchema operation.
	//
	// The mihomo config UI schema (catalogs).
	//
	// GET /admin/api/config/mihomo/schema
	ConfigSchema(ctx context.Context) (ConfigSchemaRes, error)
	// CustomCreate implements customCreate operation.
	//
	// Create a user's custom config (clone of base).
	//
	// POST /admin/api/config/mihomo/custom/create
	CustomCreate(ctx context.Context, req *CustomCreateReq) (CustomCreateRes, error)
	// CustomDelete implements customDelete operation.
	//
	// Delete a user's custom config.
	//
	// POST /admin/api/config/mihomo/custom/delete
	CustomDelete(ctx context.Context, req *CustomDeleteReq) (CustomDeleteRes, error)
	// Healthz implements healthz operation.
	//
	// Liveness probe.
	//
	// GET /healthz
	Healthz(ctx context.Context) (HealthzOK, error)
	// Login implements login operation.
	//
	// Admin sign-in.
	//
	// POST /admin/api/login
	Login(ctx context.Context, req *LoginReq) (LoginRes, error)
	// Logout implements logout operation.
	//
	// Admin sign-out.
	//
	// POST /admin/api/logout
	Logout(ctx context.Context) (*LogoutNoContent, error)
	// NodeDelete implements nodeDelete operation.
	//
	// Delete a node.
	//
	// POST /admin/api/nodes/delete
	NodeDelete(ctx context.Context, req *NodeDeleteReq) (NodeDeleteRes, error)
	// NodeSave implements nodeSave operation.
	//
	// Create or update a node.
	//
	// POST /admin/api/nodes/save
	NodeSave(ctx context.Context, req *NodeSaveReq) (NodeSaveRes, error)
	// NodesGet implements nodesGet operation.
	//
	// List nodes.
	//
	// GET /admin/api/nodes
	NodesGet(ctx context.Context) (NodesGetRes, error)
	// ProviderCheck implements providerCheck operation.
	//
	// Probe a rule-provider URL.
	//
	// POST /admin/api/config/mihomo/provider/check
	ProviderCheck(ctx context.Context, req *ProviderCheckReq) (ProviderCheckRes, error)
	// Rules implements rules operation.
	//
	// Fetch a mirrored rule-provider file.
	//
	// GET /rules/{file}
	Rules(ctx context.Context, params RulesParams) (RulesRes, error)
	// Sub implements sub operation.
	//
	// Fetch a client subscription (engine YAML).
	//
	// GET /sub/{kind}/{token}
	Sub(ctx context.Context, params SubParams) (SubRes, error)
	// UserCreate implements userCreate operation.
	//
	// Create a user.
	//
	// POST /admin/api/users/create
	UserCreate(ctx context.Context, req *UserCreateReq) (UserCreateRes, error)
	// UserDelete implements userDelete operation.
	//
	// Delete a user.
	//
	// POST /admin/api/users/delete
	UserDelete(ctx context.Context, req *UserDeleteReq) (UserDeleteRes, error)
	// UserEdit implements userEdit operation.
	//
	// Edit a user's inbound bindings.
	//
	// POST /admin/api/users/edit
	UserEdit(ctx context.Context, req *UserEditReq) (UserEditRes, error)
	// UserRecreate implements userRecreate operation.
	//
	// Recreate a user's panel clients.
	//
	// POST /admin/api/users/recreate
	UserRecreate(ctx context.Context, req *UserRecreateReq) (UserRecreateRes, error)
	// UsersGet implements usersGet operation.
	//
	// List users (paged, searchable, filterable).
	//
	// GET /admin/api/users
	UsersGet(ctx context.Context, params UsersGetParams) (UsersGetRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
