// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	ConfigCustomsOperation OperationName = "ConfigCustoms"
	ConfigGetOperation     OperationName = "ConfigGet"
	ConfigSaveOperation    OperationName = "ConfigSave"
	ConfigSchemaOperation  OperationName = "ConfigSchema"
	CustomCreateOperation  OperationName = "CustomCreate"
	CustomDeleteOperation  OperationName = "CustomDelete"
	HealthzOperation       OperationName = "Healthz"
	LoginOperation         OperationName = "Login"
	LogoutOperation        OperationName = "Logout"
	NodeDeleteOperation    OperationName = "NodeDelete"
	NodeSaveOperation      OperationName = "NodeSave"
	NodesGetOperation      OperationName = "NodesGet"
	ProviderCheckOperation OperationName = "ProviderCheck"
	RulesOperation         OperationName = "Rules"
	SubOperation           OperationName = "Sub"
	UserCreateOperation    OperationName = "UserCreate"
	UserDeleteOperation    OperationName = "UserDelete"
	UserEditOperation      OperationName = "UserEdit"
	UserRecreateOperation  OperationName = "UserRecreate"
	UsersGetOperation      OperationName = "UsersGet"
)
