// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AdminShellParams is parameters of adminShell operation.
type AdminShellParams struct {
	// The admin session cookie.
	SubgenAdmin OptString `json:",omitempty,omitzero"`
}

func unpackAdminShellParams(packed middleware.Parameters) (params AdminShellParams) {
	{
		key := middleware.ParameterKey{
			Name: "subgen_admin",
			In:   "cookie",
		}
		if v, ok := packed[key]; ok {
			params.SubgenAdmin = v.(OptString)
		}
	}
	return params
}

func decodeAdminShellParams(args [0]string, argsEscaped bool, r *http.Request) (params AdminShellParams, _ error) {
	c := uri.NewCookieDecoder(r)
	// Decode cookie: subgen_admin.
	if err := func() error {
		cfg := uri.CookieParameterDecodingConfig{
			Name:    "subgen_admin",
			Explode: true,
		}
		if err := c.HasParam(cfg); err == nil {
			if err := c.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSubgenAdminVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSubgenAdminVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.SubgenAdmin.SetTo(paramsDotSubgenAdminVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "subgen_admin",
			In:   "cookie",
			Err:  err,
		}
	}
	return params, nil
}

// AdminShellViewParams is parameters of adminShellView operation.
type AdminShellViewParams struct {
	// The client-side view segment (rendered entirely by the SPA).
	View string
	// The admin session cookie.
	SubgenAdmin OptString `json:",omitempty,omitzero"`
}

func unpackAdminShellViewParams(packed middleware.Parameters) (params AdminShellViewParams) {
	{
		key := middleware.ParameterKey{
			Name: "view",
			In:   "path",
		}
		params.View = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "subgen_admin",
			In:   "cookie",
		}
		if v, ok := packed[key]; ok {
			params.SubgenAdmin = v.(OptString)
		}
	}
	return params
}

func decodeAdminShellViewParams(args [1]string, argsEscaped bool, r *http.Request) (params AdminShellViewParams, _ error) {
	c := uri.NewCookieDecoder(r)
	// Decode path: view.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "view",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.View = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "view",
			In:   "path",
			Err:  err,
		}
	}
	// Decode cookie: subgen_admin.
	if err := func() error {
		cfg := uri.CookieParameterDecodingConfig{
			Name:    "subgen_admin",
			Explode: true,
		}
		if err := c.HasParam(cfg); err == nil {
			if err := c.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSubgenAdminVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSubgenAdminVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.SubgenAdmin.SetTo(paramsDotSubgenAdminVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "subgen_admin",
			In:   "cookie",
			Err:  err,
		}
	}
	return params, nil
}

// ConfigGetParams is parameters of configGet operation.
type ConfigGetParams struct {
	// User id whose custom config to read; omit for the base config.
	User OptInt64 `json:",omitempty,omitzero"`
}

func unpackConfigGetParams(packed middleware.Parameters) (params ConfigGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "user",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.User = v.(OptInt64)
		}
	}
	return params
}

func decodeConfigGetParams(args [0]string, argsEscaped bool, r *http.Request) (params ConfigGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: user.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "user",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUserVal int64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt64(val)
					if err != nil {
						return err
					}

					paramsDotUserVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.User.SetTo(paramsDotUserVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// LoginPageParams is parameters of loginPage operation.
type LoginPageParams struct {
	// The admin session cookie, if the visitor already has one.
	SubgenAdmin OptString `json:",omitempty,omitzero"`
}

func unpackLoginPageParams(packed middleware.Parameters) (params LoginPageParams) {
	{
		key := middleware.ParameterKey{
			Name: "subgen_admin",
			In:   "cookie",
		}
		if v, ok := packed[key]; ok {
			params.SubgenAdmin = v.(OptString)
		}
	}
	return params
}

func decodeLoginPageParams(args [0]string, argsEscaped bool, r *http.Request) (params LoginPageParams, _ error) {
	c := uri.NewCookieDecoder(r)
	// Decode cookie: subgen_admin.
	if err := func() error {
		cfg := uri.CookieParameterDecodingConfig{
			Name:    "subgen_admin",
			Explode: true,
		}
		if err := c.HasParam(cfg); err == nil {
			if err := c.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSubgenAdminVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSubgenAdminVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.SubgenAdmin.SetTo(paramsDotSubgenAdminVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "subgen_admin",
			In:   "cookie",
			Err:  err,
		}
	}
	return params, nil
}

// RulesParams is parameters of rules operation.
type RulesParams struct {
	// Mirror file name (<name><ext>).
	File string
}

func unpackRulesParams(packed middleware.Parameters) (params RulesParams) {
	{
		key := middleware.ParameterKey{
			Name: "file",
			In:   "path",
		}
		params.File = packed[key].(string)
	}
	return params
}

func decodeRulesParams(args [1]string, argsEscaped bool, r *http.Request) (params RulesParams, _ error) {
	// Decode path: file.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "file",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.File = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "file",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SubParams is parameters of sub operation.
type SubParams struct {
	// Engine/config kind (e.g. mihomo).
	Kind string
	// HMAC subscription token.
	Token string
}

func unpackSubParams(packed middleware.Parameters) (params SubParams) {
	{
		key := middleware.ParameterKey{
			Name: "kind",
			In:   "path",
		}
		params.Kind = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "token",
			In:   "path",
		}
		params.Token = packed[key].(string)
	}
	return params
}

func decodeSubParams(args [2]string, argsEscaped bool, r *http.Request) (params SubParams, _ error) {
	// Decode path: kind.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "kind",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Kind = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "kind",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: token.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "token",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Token = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "token",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UsersGetParams is parameters of usersGet operation.
type UsersGetParams struct {
	// Case-insensitive substring match on the nickname.
	Q OptString `json:",omitempty,omitzero"`
	// Repeatable node_inbounds.id — OR-filter (user has at least one).
	Inbound []int64 `json:",omitempty"`
	Page    OptInt  `json:",omitempty,omitzero"`
	PerPage OptInt  `json:",omitempty,omitzero"`
}

func unpackUsersGetParams(packed middleware.Parameters) (params UsersGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "q",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Q = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "inbound",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Inbound = v.([]int64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "page",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Page = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "perPage",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.PerPage = v.(OptInt)
		}
	}
	return params
}

func decodeUsersGetParams(args [0]string, argsEscaped bool, r *http.Request) (params UsersGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: q.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "q",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotQVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotQVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Q.SetTo(paramsDotQVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "q",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: inbound.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "inbound",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotInboundVal int64
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToInt64(val)
						if err != nil {
							return err
						}

						paramsDotInboundVal = c
						return nil
					}(); err != nil {
						return err
					}
					params.Inbound = append(params.Inbound, paramsDotInboundVal)
					return nil
				})
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "inbound",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: page.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "page",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPageVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotPageVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Page.SetTo(paramsDotPageVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "page",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: perPage.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "perPage",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPerPageVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotPerPageVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.PerPage.SetTo(paramsDotPerPageVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "perPage",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
