// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"io"
)

type AdminSession struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *AdminSession) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *AdminSession) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *AdminSession) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *AdminSession) SetRoles(val []string) {
	s.Roles = val
}

// AdminShellFound is response for AdminShell operation.
type AdminShellFound struct {
	Location OptString
}

// GetLocation returns the value of Location.
func (s *AdminShellFound) GetLocation() OptString {
	return s.Location
}

// SetLocation sets the value of Location.
func (s *AdminShellFound) SetLocation(val OptString) {
	s.Location = val
}

func (*AdminShellFound) adminShellRes() {}

type AdminShellOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s AdminShellOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*AdminShellOK) adminShellRes() {}

// AdminShellViewFound is response for AdminShellView operation.
type AdminShellViewFound struct {
	Location OptString
}

// GetLocation returns the value of Location.
func (s *AdminShellViewFound) GetLocation() OptString {
	return s.Location
}

// SetLocation sets the value of Location.
func (s *AdminShellViewFound) SetLocation(val OptString) {
	s.Location = val
}

func (*AdminShellViewFound) adminShellViewRes() {}

type AdminShellViewOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s AdminShellViewOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*AdminShellViewOK) adminShellViewRes() {}

type ConfigCustomsOK struct {
	Customs []ConfigCustomsOKCustomsItem `json:"customs"`
	Users   []ConfigCustomsOKUsersItem   `json:"users"`
}

// GetCustoms returns the value of Customs.
func (s *ConfigCustomsOK) GetCustoms() []ConfigCustomsOKCustomsItem {
	return s.Customs
}

// GetUsers returns the value of Users.
func (s *ConfigCustomsOK) GetUsers() []ConfigCustomsOKUsersItem {
	return s.Users
}

// SetCustoms sets the value of Customs.
func (s *ConfigCustomsOK) SetCustoms(val []ConfigCustomsOKCustomsItem) {
	s.Customs = val
}

// SetUsers sets the value of Users.
func (s *ConfigCustomsOK) SetUsers(val []ConfigCustomsOKUsersItem) {
	s.Users = val
}

func (*ConfigCustomsOK) configCustomsRes() {}

type ConfigCustomsOKCustomsItem struct {
	UserId int64  `json:"userId"`
	Name   string `json:"name"`
}

// GetUserId returns the value of UserId.
func (s *ConfigCustomsOKCustomsItem) GetUserId() int64 {
	return s.UserId
}

// GetName returns the value of Name.
func (s *ConfigCustomsOKCustomsItem) GetName() string {
	return s.Name
}

// SetUserId sets the value of UserId.
func (s *ConfigCustomsOKCustomsItem) SetUserId(val int64) {
	s.UserId = val
}

// SetName sets the value of Name.
func (s *ConfigCustomsOKCustomsItem) SetName(val string) {
	s.Name = val
}

type ConfigCustomsOKUsersItem struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *ConfigCustomsOKUsersItem) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *ConfigCustomsOKUsersItem) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *ConfigCustomsOKUsersItem) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ConfigCustomsOKUsersItem) SetName(val string) {
	s.Name = val
}

type ConfigGetNotFound ErrorResponse

func (*ConfigGetNotFound) configGetRes() {}

type ConfigGetUnauthorized ErrorResponse

func (*ConfigGetUnauthorized) configGetRes() {}

type ConfigSaveBadRequest ErrorResponse

func (*ConfigSaveBadRequest) configSaveRes() {}

// Merged schema.
type ConfigSaveReq struct {
	Groups                []MihomoGroup    `json:"groups"`
	Rules                 []MihomoRule     `json:"rules"`
	Providers             []MihomoProvider `json:"providers"`
	BaseYAML              string           `json:"baseYAML"`
	ProfileTitle          string           `json:"profileTitle"`
	Filename              string           `json:"filename"`
	ProfileUpdateInterval int              `json:"profileUpdateInterval"`
	UserId                OptInt64         `json:"userId"`
}

// GetGroups returns the value of Groups.
func (s *ConfigSaveReq) GetGroups() []MihomoGroup {
	return s.Groups
}

// GetRules returns the value of Rules.
func (s *ConfigSaveReq) GetRules() []MihomoRule {
	return s.Rules
}

// GetProviders returns the value of Providers.
func (s *ConfigSaveReq) GetProviders() []MihomoProvider {
	return s.Providers
}

// GetBaseYAML returns the value of BaseYAML.
func (s *ConfigSaveReq) GetBaseYAML() string {
	return s.BaseYAML
}

// GetProfileTitle returns the value of ProfileTitle.
func (s *ConfigSaveReq) GetProfileTitle() string {
	return s.ProfileTitle
}

// GetFilename returns the value of Filename.
func (s *ConfigSaveReq) GetFilename() string {
	return s.Filename
}

// GetProfileUpdateInterval returns the value of ProfileUpdateInterval.
func (s *ConfigSaveReq) GetProfileUpdateInterval() int {
	return s.ProfileUpdateInterval
}

// GetUserId returns the value of UserId.
func (s *ConfigSaveReq) GetUserId() OptInt64 {
	return s.UserId
}

// SetGroups sets the value of Groups.
func (s *ConfigSaveReq) SetGroups(val []MihomoGroup) {
	s.Groups = val
}

// SetRules sets the value of Rules.
func (s *ConfigSaveReq) SetRules(val []MihomoRule) {
	s.Rules = val
}

// SetProviders sets the value of Providers.
func (s *ConfigSaveReq) SetProviders(val []MihomoProvider) {
	s.Providers = val
}

// SetBaseYAML sets the value of BaseYAML.
func (s *ConfigSaveReq) SetBaseYAML(val string) {
	s.BaseYAML = val
}

// SetProfileTitle sets the value of ProfileTitle.
func (s *ConfigSaveReq) SetProfileTitle(val string) {
	s.ProfileTitle = val
}

// SetFilename sets the value of Filename.
func (s *ConfigSaveReq) SetFilename(val string) {
	s.Filename = val
}

// SetProfileUpdateInterval sets the value of ProfileUpdateInterval.
func (s *ConfigSaveReq) SetProfileUpdateInterval(val int) {
	s.ProfileUpdateInterval = val
}

// SetUserId sets the value of UserId.
func (s *ConfigSaveReq) SetUserId(val OptInt64) {
	s.UserId = val
}

type ConfigSaveUnauthorized ErrorResponse

func (*ConfigSaveUnauthorized) configSaveRes() {}

type ConfigSchemaOK struct {
	Actions       []ConfigSchemaOKActionsItem `json:"actions"`
	RuleProvider  ConfigSchemaOKRuleProvider  `json:"ruleProvider"`
	ProxyGroup    ConfigSchemaOKProxyGroup    `json:"proxyGroup"`
	Rules         ConfigSchemaOKRules         `json:"rules"`
	GeneratedKeys []string                    `json:"generatedKeys"`
}

// GetActions returns the value of Actions.
func (s *ConfigSchemaOK) GetActions() []ConfigSchemaOKActionsItem {
	return s.Actions
}

// GetRuleProvider returns the value of RuleProvider.
func (s *ConfigSchemaOK) GetRuleProvider() ConfigSchemaOKRuleProvider {
	return s.RuleProvider
}

// GetProxyGroup returns the value of ProxyGroup.
func (s *ConfigSchemaOK) GetProxyGroup() ConfigSchemaOKProxyGroup {
	return s.ProxyGroup
}

// GetRules returns the value of Rules.
func (s *ConfigSchemaOK) GetRules() ConfigSchemaOKRules {
	return s.Rules
}

// GetGeneratedKeys returns the value of GeneratedKeys.
func (s *ConfigSchemaOK) GetGeneratedKeys() []string {
	return s.GeneratedKeys
}

// SetActions sets the value of Actions.
func (s *ConfigSchemaOK) SetActions(val []ConfigSchemaOKActionsItem) {
	s.Actions = val
}

// SetRuleProvider sets the value of RuleProvider.
func (s *ConfigSchemaOK) SetRuleProvider(val ConfigSchemaOKRuleProvider) {
	s.RuleProvider = val
}

// SetProxyGroup sets the value of ProxyGroup.
func (s *ConfigSchemaOK) SetProxyGroup(val ConfigSchemaOKProxyGroup) {
	s.ProxyGroup = val
}

// SetRules sets the value of Rules.
func (s *ConfigSchemaOK) SetRules(val ConfigSchemaOKRules) {
	s.Rules = val
}

// SetGeneratedKeys sets the value of GeneratedKeys.
func (s *ConfigSchemaOK) SetGeneratedKeys(val []string) {
	s.GeneratedKeys = val
}

func (*ConfigSchemaOK) configSchemaRes() {}

type ConfigSchemaOKActionsItem struct {
	Kind  string `json:"kind"`
	Label string `json:"label"`
}

// GetKind returns the value of Kind.
func (s *ConfigSchemaOKActionsItem) GetKind() string {
	return s.Kind
}

// GetLabel returns the value of Label.
func (s *ConfigSchemaOKActionsItem) GetLabel() string {
	return s.Label
}

// SetKind sets the value of Kind.
func (s *ConfigSchemaOKActionsItem) SetKind(val string) {
	s.Kind = val
}

// SetLabel sets the value of Label.
func (s *ConfigSchemaOKActionsItem) SetLabel(val string) {
	s.Label = val
}

type ConfigSchemaOKProxyGroup struct {
	Types []ConfigSchemaOKProxyGroupTypesItem `json:"types"`
}

// GetTypes returns the value of Types.
func (s *ConfigSchemaOKProxyGroup) GetTypes() []ConfigSchemaOKProxyGroupTypesItem {
	return s.Types
}

// SetTypes sets the value of Types.
func (s *ConfigSchemaOKProxyGroup) SetTypes(val []ConfigSchemaOKProxyGroupTypesItem) {
	s.Types = val
}

type ConfigSchemaOKProxyGroupTypesItem struct {
	Type            string   `json:"type"`
	UsesHealthCheck bool     `json:"usesHealthCheck"`
	UsesTolerance   bool     `json:"usesTolerance"`
	Items           []string `json:"items"`
}

// GetType returns the value of Type.
func (s *ConfigSchemaOKProxyGroupTypesItem) GetType() string {
	return s.Type
}

// GetUsesHealthCheck returns the value of UsesHealthCheck.
func (s *ConfigSchemaOKProxyGroupTypesItem) GetUsesHealthCheck() bool {
	return s.UsesHealthCheck
}

// GetUsesTolerance returns the value of UsesTolerance.
func (s *ConfigSchemaOKProxyGroupTypesItem) GetUsesTolerance() bool {
	return s.UsesTolerance
}

// GetItems returns the value of Items.
func (s *ConfigSchemaOKProxyGroupTypesItem) GetItems() []string {
	return s.Items
}

// SetType sets the value of Type.
func (s *ConfigSchemaOKProxyGroupTypesItem) SetType(val string) {
	s.Type = val
}

// SetUsesHealthCheck sets the value of UsesHealthCheck.
func (s *ConfigSchemaOKProxyGroupTypesItem) SetUsesHealthCheck(val bool) {
	s.UsesHealthCheck = val
}

// SetUsesTolerance sets the value of UsesTolerance.
func (s *ConfigSchemaOKProxyGroupTypesItem) SetUsesTolerance(val bool) {
	s.UsesTolerance = val
}

// SetItems sets the value of Items.
func (s *ConfigSchemaOKProxyGroupTypesItem) SetItems(val []string) {
	s.Items = val
}

type ConfigSchemaOKRuleProvider struct {
	Behaviors []string `json:"behaviors"`
	Formats   []string `json:"formats"`
}

// GetBehaviors returns the value of Behaviors.
func (s *ConfigSchemaOKRuleProvider) GetBehaviors() []string {
	return s.Behaviors
}

// GetFormats returns the value of Formats.
func (s *ConfigSchemaOKRuleProvider) GetFormats() []string {
	return s.Formats
}

// SetBehaviors sets the value of Behaviors.
func (s *ConfigSchemaOKRuleProvider) SetBehaviors(val []string) {
	s.Behaviors = val
}

// SetFormats sets the value of Formats.
func (s *ConfigSchemaOKRuleProvider) SetFormats(val []string) {
	s.Formats = val
}

type ConfigSchemaOKRules struct {
	Types []ConfigSchemaOKRulesTypesItem `json:"types"`
}

// GetTypes returns the value of Types.
func (s *ConfigSchemaOKRules) GetTypes() []ConfigSchemaOKRulesTypesItem {
	return s.Types
}

// SetTypes sets the value of Types.
func (s *ConfigSchemaOKRules) SetTypes(val []ConfigSchemaOKRulesTypesItem) {
	s.Types = val
}

type ConfigSchemaOKRulesTypesItem struct {
	Type              string   `json:"type"`
	TakesProvider     bool     `json:"takesProvider"`
	SupportsNoResolve bool     `json:"supportsNoResolve"`
	IsMatch           bool     `json:"isMatch"`
	IsLogical         bool     `json:"isLogical"`
	Destinations      []string `json:"destinations"`
}

// GetType returns the value of Type.
func (s *ConfigSchemaOKRulesTypesItem) GetType() string {
	return s.Type
}

// GetTakesProvider returns the value of TakesProvider.
func (s *ConfigSchemaOKRulesTypesItem) GetTakesProvider() bool {
	return s.TakesProvider
}

// GetSupportsNoResolve returns the value of SupportsNoResolve.
func (s *ConfigSchemaOKRulesTypesItem) GetSupportsNoResolve() bool {
	return s.SupportsNoResolve
}

// GetIsMatch returns the value of IsMatch.
func (s *ConfigSchemaOKRulesTypesItem) GetIsMatch() bool {
	return s.IsMatch
}

// GetIsLogical returns the value of IsLogical.
func (s *ConfigSchemaOKRulesTypesItem) GetIsLogical() bool {
	return s.IsLogical
}

// GetDestinations returns the value of Destinations.
func (s *ConfigSchemaOKRulesTypesItem) GetDestinations() []string {
	return s.Destinations
}

// SetType sets the value of Type.
func (s *ConfigSchemaOKRulesTypesItem) SetType(val string) {
	s.Type = val
}

// SetTakesProvider sets the value of TakesProvider.
func (s *ConfigSchemaOKRulesTypesItem) SetTakesProvider(val bool) {
	s.TakesProvider = val
}

// SetSupportsNoResolve sets the value of SupportsNoResolve.
func (s *ConfigSchemaOKRulesTypesItem) SetSupportsNoResolve(val bool) {
	s.SupportsNoResolve = val
}

// SetIsMatch sets the value of IsMatch.
func (s *ConfigSchemaOKRulesTypesItem) SetIsMatch(val bool) {
	s.IsMatch = val
}

// SetIsLogical sets the value of IsLogical.
func (s *ConfigSchemaOKRulesTypesItem) SetIsLogical(val bool) {
	s.IsLogical = val
}

// SetDestinations sets the value of Destinations.
func (s *ConfigSchemaOKRulesTypesItem) SetDestinations(val []string) {
	s.Destinations = val
}

type CustomCreateBadRequest ErrorResponse

func (*CustomCreateBadRequest) customCreateRes() {}

type CustomCreateReq struct {
	UserId int64 `json:"userId"`
}

// GetUserId returns the value of UserId.
func (s *CustomCreateReq) GetUserId() int64 {
	return s.UserId
}

// SetUserId sets the value of UserId.
func (s *CustomCreateReq) SetUserId(val int64) {
	s.UserId = val
}

type CustomCreateUnauthorized ErrorResponse

func (*CustomCreateUnauthorized) customCreateRes() {}

type CustomDeleteBadRequest ErrorResponse

func (*CustomDeleteBadRequest) customDeleteRes() {}

type CustomDeleteReq struct {
	UserId int64 `json:"userId"`
}

// GetUserId returns the value of UserId.
func (s *CustomDeleteReq) GetUserId() int64 {
	return s.UserId
}

// SetUserId sets the value of UserId.
func (s *CustomDeleteReq) SetUserId(val int64) {
	s.UserId = val
}

type CustomDeleteUnauthorized ErrorResponse

func (*CustomDeleteUnauthorized) customDeleteRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Human-readable (generic) error message for the SPA to toast.
	ErrMessage string `json:"errMessage"`
}

// GetErrMessage returns the value of ErrMessage.
func (s *ErrorResponse) GetErrMessage() string {
	return s.ErrMessage
}

// SetErrMessage sets the value of ErrMessage.
func (s *ErrorResponse) SetErrMessage(val string) {
	s.ErrMessage = val
}

func (*ErrorResponse) configCustomsRes() {}
func (*ErrorResponse) configSchemaRes()  {}
func (*ErrorResponse) loginRes()         {}
func (*ErrorResponse) nodesGetRes()      {}
func (*ErrorResponse) usersGetRes()      {}

type HealthzOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s HealthzOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// LoginPageFound is response for LoginPage operation.
type LoginPageFound struct {
	Location OptString
}

// GetLocation returns the value of Location.
func (s *LoginPageFound) GetLocation() OptString {
	return s.Location
}

// SetLocation sets the value of Location.
func (s *LoginPageFound) SetLocation(val OptString) {
	s.Location = val
}

func (*LoginPageFound) loginPageRes() {}

type LoginPageOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s LoginPageOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*LoginPageOK) loginPageRes() {}

type LoginReq struct {
	User     string `json:"user"`
	Password string `json:"password"`
}

// GetUser returns the value of User.
func (s *LoginReq) GetUser() string {
	return s.User
}

// GetPassword returns the value of Password.
func (s *LoginReq) GetPassword() string {
	return s.Password
}

// SetUser sets the value of User.
func (s *LoginReq) SetUser(val string) {
	s.User = val
}

// SetPassword sets the value of Password.
func (s *LoginReq) SetPassword(val string) {
	s.Password = val
}

// LogoutNoContent is response for Logout operation.
type LogoutNoContent struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *LogoutNoContent) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *LogoutNoContent) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// Ref: #/components/schemas/MessageResponse
type MessageResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *MessageResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *MessageResponse) SetMessage(val string) {
	s.Message = val
}

func (*MessageResponse) configSaveRes()    {}
func (*MessageResponse) customCreateRes()  {}
func (*MessageResponse) customDeleteRes()  {}
func (*MessageResponse) nodeDeleteRes()    {}
func (*MessageResponse) nodeSaveRes()      {}
func (*MessageResponse) providerCheckRes() {}
func (*MessageResponse) userCreateRes()    {}
func (*MessageResponse) userDeleteRes()    {}
func (*MessageResponse) userEditRes()      {}
func (*MessageResponse) userRecreateRes()  {}

// MessageResponseHeaders wraps MessageResponse with response headers.
type MessageResponseHeaders struct {
	SetCookie OptString
	Response  MessageResponse
}

// GetSetCookie returns the value of SetCookie.
func (s *MessageResponseHeaders) GetSetCookie() OptString {
	return s.SetCookie
}

// GetResponse returns the value of Response.
func (s *MessageResponseHeaders) GetResponse() MessageResponse {
	return s.Response
}

// SetSetCookie sets the value of SetCookie.
func (s *MessageResponseHeaders) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// SetResponse sets the value of Response.
func (s *MessageResponseHeaders) SetResponse(val MessageResponse) {
	s.Response = val
}

func (*MessageResponseHeaders) loginRes() {}

// Ref: #/components/schemas/MihomoConfig
type MihomoConfig struct {
	Groups                []MihomoGroup    `json:"groups"`
	Rules                 []MihomoRule     `json:"rules"`
	Providers             []MihomoProvider `json:"providers"`
	BaseYAML              string           `json:"baseYAML"`
	ProfileTitle          string           `json:"profileTitle"`
	Filename              string           `json:"filename"`
	ProfileUpdateInterval int              `json:"profileUpdateInterval"`
}

// GetGroups returns the value of Groups.
func (s *MihomoConfig) GetGroups() []MihomoGroup {
	return s.Groups
}

// GetRules returns the value of Rules.
func (s *MihomoConfig) GetRules() []MihomoRule {
	return s.Rules
}

// GetProviders returns the value of Providers.
func (s *MihomoConfig) GetProviders() []MihomoProvider {
	return s.Providers
}

// GetBaseYAML returns the value of BaseYAML.
func (s *MihomoConfig) GetBaseYAML() string {
	return s.BaseYAML
}

// GetProfileTitle returns the value of ProfileTitle.
func (s *MihomoConfig) GetProfileTitle() string {
	return s.ProfileTitle
}

// GetFilename returns the value of Filename.
func (s *MihomoConfig) GetFilename() string {
	return s.Filename
}

// GetProfileUpdateInterval returns the value of ProfileUpdateInterval.
func (s *MihomoConfig) GetProfileUpdateInterval() int {
	return s.ProfileUpdateInterval
}

// SetGroups sets the value of Groups.
func (s *MihomoConfig) SetGroups(val []MihomoGroup) {
	s.Groups = val
}

// SetRules sets the value of Rules.
func (s *MihomoConfig) SetRules(val []MihomoRule) {
	s.Rules = val
}

// SetProviders sets the value of Providers.
func (s *MihomoConfig) SetProviders(val []MihomoProvider) {
	s.Providers = val
}

// SetBaseYAML sets the value of BaseYAML.
func (s *MihomoConfig) SetBaseYAML(val string) {
	s.BaseYAML = val
}

// SetProfileTitle sets the value of ProfileTitle.
func (s *MihomoConfig) SetProfileTitle(val string) {
	s.ProfileTitle = val
}

// SetFilename sets the value of Filename.
func (s *MihomoConfig) SetFilename(val string) {
	s.Filename = val
}

// SetProfileUpdateInterval sets the value of ProfileUpdateInterval.
func (s *MihomoConfig) SetProfileUpdateInterval(val int) {
	s.ProfileUpdateInterval = val
}

func (*MihomoConfig) configGetRes() {}

// Ref: #/components/schemas/MihomoGroup
type MihomoGroup struct {
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	URL       string      `json:"url"`
	Interval  OptInt      `json:"interval"`
	Tolerance OptInt      `json:"tolerance"`
	Lazy      OptBool     `json:"lazy"`
	Members   []PolicyRef `json:"members"`
}

// GetName returns the value of Name.
func (s *MihomoGroup) GetName() string {
	return s.Name
}

// GetType returns the value of Type.
func (s *MihomoGroup) GetType() string {
	return s.Type
}

// GetURL returns the value of URL.
func (s *MihomoGroup) GetURL() string {
	return s.URL
}

// GetInterval returns the value of Interval.
func (s *MihomoGroup) GetInterval() OptInt {
	return s.Interval
}

// GetTolerance returns the value of Tolerance.
func (s *MihomoGroup) GetTolerance() OptInt {
	return s.Tolerance
}

// GetLazy returns the value of Lazy.
func (s *MihomoGroup) GetLazy() OptBool {
	return s.Lazy
}

// GetMembers returns the value of Members.
func (s *MihomoGroup) GetMembers() []PolicyRef {
	return s.Members
}

// SetName sets the value of Name.
func (s *MihomoGroup) SetName(val string) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *MihomoGroup) SetType(val string) {
	s.Type = val
}

// SetURL sets the value of URL.
func (s *MihomoGroup) SetURL(val string) {
	s.URL = val
}

// SetInterval sets the value of Interval.
func (s *MihomoGroup) SetInterval(val OptInt) {
	s.Interval = val
}

// SetTolerance sets the value of Tolerance.
func (s *MihomoGroup) SetTolerance(val OptInt) {
	s.Tolerance = val
}

// SetLazy sets the value of Lazy.
func (s *MihomoGroup) SetLazy(val OptBool) {
	s.Lazy = val
}

// SetMembers sets the value of Members.
func (s *MihomoGroup) SetMembers(val []PolicyRef) {
	s.Members = val
}

// Ref: #/components/schemas/MihomoProvider
type MihomoProvider struct {
	Name           string `json:"name"`
	Behavior       string `json:"behavior"`
	Format         string `json:"format"`
	URL            string `json:"url"`
	Interval       int    `json:"interval"`
	Mirror         bool   `json:"mirror"`
	MirrorInterval int    `json:"mirrorInterval"`
}

// GetName returns the value of Name.
func (s *MihomoProvider) GetName() string {
	return s.Name
}

// GetBehavior returns the value of Behavior.
func (s *MihomoProvider) GetBehavior() string {
	return s.Behavior
}

// GetFormat returns the value of Format.
func (s *MihomoProvider) GetFormat() string {
	return s.Format
}

// GetURL returns the value of URL.
func (s *MihomoProvider) GetURL() string {
	return s.URL
}

// GetInterval returns the value of Interval.
func (s *MihomoProvider) GetInterval() int {
	return s.Interval
}

// GetMirror returns the value of Mirror.
func (s *MihomoProvider) GetMirror() bool {
	return s.Mirror
}

// GetMirrorInterval returns the value of MirrorInterval.
func (s *MihomoProvider) GetMirrorInterval() int {
	return s.MirrorInterval
}

// SetName sets the value of Name.
func (s *MihomoProvider) SetName(val string) {
	s.Name = val
}

// SetBehavior sets the value of Behavior.
func (s *MihomoProvider) SetBehavior(val string) {
	s.Behavior = val
}

// SetFormat sets the value of Format.
func (s *MihomoProvider) SetFormat(val string) {
	s.Format = val
}

// SetURL sets the value of URL.
func (s *MihomoProvider) SetURL(val string) {
	s.URL = val
}

// SetInterval sets the value of Interval.
func (s *MihomoProvider) SetInterval(val int) {
	s.Interval = val
}

// SetMirror sets the value of Mirror.
func (s *MihomoProvider) SetMirror(val bool) {
	s.Mirror = val
}

// SetMirrorInterval sets the value of MirrorInterval.
func (s *MihomoProvider) SetMirrorInterval(val int) {
	s.MirrorInterval = val
}

// Ref: #/components/schemas/MihomoRule
type MihomoRule struct {
	Type        string       `json:"type"`
	Value       OptString    `json:"value"`
	ProviderIdx OptInt       `json:"providerIdx"`
	NoResolve   OptBool      `json:"noResolve"`
	Target      OptPolicyRef `json:"target"`
	Children    []MihomoRule `json:"children"`
}

// GetType returns the value of Type.
func (s *MihomoRule) GetType() string {
	return s.Type
}

// GetValue returns the value of Value.
func (s *MihomoRule) GetValue() OptString {
	return s.Value
}

// GetProviderIdx returns the value of ProviderIdx.
func (s *MihomoRule) GetProviderIdx() OptInt {
	return s.ProviderIdx
}

// GetNoResolve returns the value of NoResolve.
func (s *MihomoRule) GetNoResolve() OptBool {
	return s.NoResolve
}

// GetTarget returns the value of Target.
func (s *MihomoRule) GetTarget() OptPolicyRef {
	return s.Target
}

// GetChildren returns the value of Children.
func (s *MihomoRule) GetChildren() []MihomoRule {
	return s.Children
}

// SetType sets the value of Type.
func (s *MihomoRule) SetType(val string) {
	s.Type = val
}

// SetValue sets the value of Value.
func (s *MihomoRule) SetValue(val OptString) {
	s.Value = val
}

// SetProviderIdx sets the value of ProviderIdx.
func (s *MihomoRule) SetProviderIdx(val OptInt) {
	s.ProviderIdx = val
}

// SetNoResolve sets the value of NoResolve.
func (s *MihomoRule) SetNoResolve(val OptBool) {
	s.NoResolve = val
}

// SetTarget sets the value of Target.
func (s *MihomoRule) SetTarget(val OptPolicyRef) {
	s.Target = val
}

// SetChildren sets the value of Children.
func (s *MihomoRule) SetChildren(val []MihomoRule) {
	s.Children = val
}

type NodeDeleteBadRequest ErrorResponse

func (*NodeDeleteBadRequest) nodeDeleteRes() {}

type NodeDeleteReq struct {
	ID int64 `json:"id"`
}

// GetID returns the value of ID.
func (s *NodeDeleteReq) GetID() int64 {
	return s.ID
}

// SetID sets the value of ID.
func (s *NodeDeleteReq) SetID(val int64) {
	s.ID = val
}

type NodeDeleteUnauthorized ErrorResponse

func (*NodeDeleteUnauthorized) nodeDeleteRes() {}

type NodeSaveBadRequest ErrorResponse

func (*NodeSaveBadRequest) nodeSaveRes() {}

type NodeSaveConflict ErrorResponse

func (*NodeSaveConflict) nodeSaveRes() {}

type NodeSaveReq struct {
	// 0/absent = create; >0 = update.
	ID            OptInt64 `json:"id"`
	Name          string   `json:"name"`
	VpnHost       string   `json:"vpnHost"`
	PanelBaseURL  string   `json:"panelBaseURL"`
	PanelBasePath string   `json:"panelBasePath"`
	// API token; empty on update keeps the stored one.
	Token    OptString                 `json:"token"`
	Inbounds []NodeSaveReqInboundsItem `json:"inbounds"`
}

// GetID returns the value of ID.
func (s *NodeSaveReq) GetID() OptInt64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *NodeSaveReq) GetName() string {
	return s.Name
}

// GetVpnHost returns the value of VpnHost.
func (s *NodeSaveReq) GetVpnHost() string {
	return s.VpnHost
}

// GetPanelBaseURL returns the value of PanelBaseURL.
func (s *NodeSaveReq) GetPanelBaseURL() string {
	return s.PanelBaseURL
}

// GetPanelBasePath returns the value of PanelBasePath.
func (s *NodeSaveReq) GetPanelBasePath() string {
	return s.PanelBasePath
}

// GetToken returns the value of Token.
func (s *NodeSaveReq) GetToken() OptString {
	return s.Token
}

// GetInbounds returns the value of Inbounds.
func (s *NodeSaveReq) GetInbounds() []NodeSaveReqInboundsItem {
	return s.Inbounds
}

// SetID sets the value of ID.
func (s *NodeSaveReq) SetID(val OptInt64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *NodeSaveReq) SetName(val string) {
	s.Name = val
}

// SetVpnHost sets the value of VpnHost.
func (s *NodeSaveReq) SetVpnHost(val string) {
	s.VpnHost = val
}

// SetPanelBaseURL sets the value of PanelBaseURL.
func (s *NodeSaveReq) SetPanelBaseURL(val string) {
	s.PanelBaseURL = val
}

// SetPanelBasePath sets the value of PanelBasePath.
func (s *NodeSaveReq) SetPanelBasePath(val string) {
	s.PanelBasePath = val
}

// SetToken sets the value of Token.
func (s *NodeSaveReq) SetToken(val OptString) {
	s.Token = val
}

// SetInbounds sets the value of Inbounds.
func (s *NodeSaveReq) SetInbounds(val []NodeSaveReqInboundsItem) {
	s.Inbounds = val
}

type NodeSaveReqInboundsItem struct {
	// 0 = new inbound; >0 = existing node_inbounds.id.
	ID   OptInt64 `json:"id"`
	Name string   `json:"name"`
	Port int      `json:"port"`
}

// GetID returns the value of ID.
func (s *NodeSaveReqInboundsItem) GetID() OptInt64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *NodeSaveReqInboundsItem) GetName() string {
	return s.Name
}

// GetPort returns the value of Port.
func (s *NodeSaveReqInboundsItem) GetPort() int {
	return s.Port
}

// SetID sets the value of ID.
func (s *NodeSaveReqInboundsItem) SetID(val OptInt64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *NodeSaveReqInboundsItem) SetName(val string) {
	s.Name = val
}

// SetPort sets the value of Port.
func (s *NodeSaveReqInboundsItem) SetPort(val int) {
	s.Port = val
}

type NodeSaveUnauthorized ErrorResponse

func (*NodeSaveUnauthorized) nodeSaveRes() {}

type NodesGetOK struct {
	Nodes []NodesGetOKNodesItem `json:"nodes"`
}

// GetNodes returns the value of Nodes.
func (s *NodesGetOK) GetNodes() []NodesGetOKNodesItem {
	return s.Nodes
}

// SetNodes sets the value of Nodes.
func (s *NodesGetOK) SetNodes(val []NodesGetOKNodesItem) {
	s.Nodes = val
}

func (*NodesGetOK) nodesGetRes() {}

type NodesGetOKNodesItem struct {
	ID            int64                             `json:"id"`
	Name          string                            `json:"name"`
	VpnHost       string                            `json:"vpnHost"`
	PanelBaseURL  string                            `json:"panelBaseURL"`
	PanelBasePath string                            `json:"panelBasePath"`
	Inbounds      []NodesGetOKNodesItemInboundsItem `json:"inbounds"`
}

// GetID returns the value of ID.
func (s *NodesGetOKNodesItem) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *NodesGetOKNodesItem) GetName() string {
	return s.Name
}

// GetVpnHost returns the value of VpnHost.
func (s *NodesGetOKNodesItem) GetVpnHost() string {
	return s.VpnHost
}

// GetPanelBaseURL returns the value of PanelBaseURL.
func (s *NodesGetOKNodesItem) GetPanelBaseURL() string {
	return s.PanelBaseURL
}

// GetPanelBasePath returns the value of PanelBasePath.
func (s *NodesGetOKNodesItem) GetPanelBasePath() string {
	return s.PanelBasePath
}

// GetInbounds returns the value of Inbounds.
func (s *NodesGetOKNodesItem) GetInbounds() []NodesGetOKNodesItemInboundsItem {
	return s.Inbounds
}

// SetID sets the value of ID.
func (s *NodesGetOKNodesItem) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *NodesGetOKNodesItem) SetName(val string) {
	s.Name = val
}

// SetVpnHost sets the value of VpnHost.
func (s *NodesGetOKNodesItem) SetVpnHost(val string) {
	s.VpnHost = val
}

// SetPanelBaseURL sets the value of PanelBaseURL.
func (s *NodesGetOKNodesItem) SetPanelBaseURL(val string) {
	s.PanelBaseURL = val
}

// SetPanelBasePath sets the value of PanelBasePath.
func (s *NodesGetOKNodesItem) SetPanelBasePath(val string) {
	s.PanelBasePath = val
}

// SetInbounds sets the value of Inbounds.
func (s *NodesGetOKNodesItem) SetInbounds(val []NodesGetOKNodesItemInboundsItem) {
	s.Inbounds = val
}

type NodesGetOKNodesItemInboundsItem struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Port int    `json:"port"`
}

// GetID returns the value of ID.
func (s *NodesGetOKNodesItemInboundsItem) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *NodesGetOKNodesItemInboundsItem) GetName() string {
	return s.Name
}

// GetPort returns the value of Port.
func (s *NodesGetOKNodesItemInboundsItem) GetPort() int {
	return s.Port
}

// SetID sets the value of ID.
func (s *NodesGetOKNodesItemInboundsItem) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *NodesGetOKNodesItemInboundsItem) SetName(val string) {
	s.Name = val
}

// SetPort sets the value of Port.
func (s *NodesGetOKNodesItemInboundsItem) SetPort(val int) {
	s.Port = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPolicyRef returns new OptPolicyRef with value set to v.
func NewOptPolicyRef(v PolicyRef) OptPolicyRef {
	return OptPolicyRef{
		Value: v,
		Set:   true,
	}
}

// OptPolicyRef is optional PolicyRef.
type OptPolicyRef struct {
	Value PolicyRef
	Set   bool
}

// IsSet returns true if OptPolicyRef was set.
func (o OptPolicyRef) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPolicyRef) Reset() {
	var v PolicyRef
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPolicyRef) SetTo(v PolicyRef) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPolicyRef) Get() (v PolicyRef, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPolicyRef) Or(d PolicyRef) PolicyRef {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PolicyRef
type PolicyRef struct {
	Kind      string   `json:"kind"`
	InboundId OptInt64 `json:"inboundId"`
	GroupIdx  OptInt   `json:"groupIdx"`
}

// GetKind returns the value of Kind.
func (s *PolicyRef) GetKind() string {
	return s.Kind
}

// GetInboundId returns the value of InboundId.
func (s *PolicyRef) GetInboundId() OptInt64 {
	return s.InboundId
}

// GetGroupIdx returns the value of GroupIdx.
func (s *PolicyRef) GetGroupIdx() OptInt {
	return s.GroupIdx
}

// SetKind sets the value of Kind.
func (s *PolicyRef) SetKind(val string) {
	s.Kind = val
}

// SetInboundId sets the value of InboundId.
func (s *PolicyRef) SetInboundId(val OptInt64) {
	s.InboundId = val
}

// SetGroupIdx sets the value of GroupIdx.
func (s *PolicyRef) SetGroupIdx(val OptInt) {
	s.GroupIdx = val
}

type ProviderCheckBadRequest ErrorResponse

func (*ProviderCheckBadRequest) providerCheckRes() {}

type ProviderCheckReq struct {
	URL    string `json:"url"`
	Format string `json:"format"`
}

// GetURL returns the value of URL.
func (s *ProviderCheckReq) GetURL() string {
	return s.URL
}

// GetFormat returns the value of Format.
func (s *ProviderCheckReq) GetFormat() string {
	return s.Format
}

// SetURL sets the value of URL.
func (s *ProviderCheckReq) SetURL(val string) {
	s.URL = val
}

// SetFormat sets the value of Format.
func (s *ProviderCheckReq) SetFormat(val string) {
	s.Format = val
}

type ProviderCheckUnauthorized ErrorResponse

func (*ProviderCheckUnauthorized) providerCheckRes() {}

type RulesNotFound struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s RulesNotFound) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*RulesNotFound) rulesRes() {}

type RulesOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s RulesOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// RulesOKHeaders wraps RulesOK with response headers.
type RulesOKHeaders struct {
	XContentTypeOptions OptString
	Response            RulesOK
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *RulesOKHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetResponse returns the value of Response.
func (s *RulesOKHeaders) GetResponse() RulesOK {
	return s.Response
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *RulesOKHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetResponse sets the value of Response.
func (s *RulesOKHeaders) SetResponse(val RulesOK) {
	s.Response = val
}

func (*RulesOKHeaders) rulesRes() {}

type SubNotFound struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s SubNotFound) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*SubNotFound) subRes() {}

type SubOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s SubOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// SubOKHeaders wraps SubOK with response headers.
type SubOKHeaders struct {
	ContentDisposition    OptString
	ProfileTitle          OptString
	ProfileUpdateInterval OptString
	SubscriptionUserinfo  OptString
	Response              SubOK
}

// GetContentDisposition returns the value of ContentDisposition.
func (s *SubOKHeaders) GetContentDisposition() OptString {
	return s.ContentDisposition
}

// GetProfileTitle returns the value of ProfileTitle.
func (s *SubOKHeaders) GetProfileTitle() OptString {
	return s.ProfileTitle
}

// GetProfileUpdateInterval returns the value of ProfileUpdateInterval.
func (s *SubOKHeaders) GetProfileUpdateInterval() OptString {
	return s.ProfileUpdateInterval
}

// GetSubscriptionUserinfo returns the value of SubscriptionUserinfo.
func (s *SubOKHeaders) GetSubscriptionUserinfo() OptString {
	return s.SubscriptionUserinfo
}

// GetResponse returns the value of Response.
func (s *SubOKHeaders) GetResponse() SubOK {
	return s.Response
}

// SetContentDisposition sets the value of ContentDisposition.
func (s *SubOKHeaders) SetContentDisposition(val OptString) {
	s.ContentDisposition = val
}

// SetProfileTitle sets the value of ProfileTitle.
func (s *SubOKHeaders) SetProfileTitle(val OptString) {
	s.ProfileTitle = val
}

// SetProfileUpdateInterval sets the value of ProfileUpdateInterval.
func (s *SubOKHeaders) SetProfileUpdateInterval(val OptString) {
	s.ProfileUpdateInterval = val
}

// SetSubscriptionUserinfo sets the value of SubscriptionUserinfo.
func (s *SubOKHeaders) SetSubscriptionUserinfo(val OptString) {
	s.SubscriptionUserinfo = val
}

// SetResponse sets the value of Response.
func (s *SubOKHeaders) SetResponse(val SubOK) {
	s.Response = val
}

func (*SubOKHeaders) subRes() {}

type UserCreateBadRequest ErrorResponse

func (*UserCreateBadRequest) userCreateRes() {}

type UserCreateConflict ErrorResponse

func (*UserCreateConflict) userCreateRes() {}

type UserCreateReq struct {
	Name string `json:"name"`
	// Optional free-text note, shown only in the admin UI (length validated server-side).
	Description OptString `json:"description"`
	InboundIDs  []int64   `json:"inboundIDs"`
}

// GetName returns the value of Name.
func (s *UserCreateReq) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *UserCreateReq) GetDescription() OptString {
	return s.Description
}

// GetInboundIDs returns the value of InboundIDs.
func (s *UserCreateReq) GetInboundIDs() []int64 {
	return s.InboundIDs
}

// SetName sets the value of Name.
func (s *UserCreateReq) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *UserCreateReq) SetDescription(val OptString) {
	s.Description = val
}

// SetInboundIDs sets the value of InboundIDs.
func (s *UserCreateReq) SetInboundIDs(val []int64) {
	s.InboundIDs = val
}

type UserCreateUnauthorized ErrorResponse

func (*UserCreateUnauthorized) userCreateRes() {}

type UserDeleteBadRequest ErrorResponse

func (*UserDeleteBadRequest) userDeleteRes() {}

type UserDeleteReq struct {
	ID int64 `json:"id"`
}

// GetID returns the value of ID.
func (s *UserDeleteReq) GetID() int64 {
	return s.ID
}

// SetID sets the value of ID.
func (s *UserDeleteReq) SetID(val int64) {
	s.ID = val
}

type UserDeleteUnauthorized ErrorResponse

func (*UserDeleteUnauthorized) userDeleteRes() {}

type UserEditBadRequest ErrorResponse

func (*UserEditBadRequest) userEditRes() {}

type UserEditReq struct {
	ID int64 `json:"id"`
	// Optional free-text note, shown only in the admin UI (length validated server-side).
	Description OptString `json:"description"`
	InboundIDs  []int64   `json:"inboundIDs"`
}

// GetID returns the value of ID.
func (s *UserEditReq) GetID() int64 {
	return s.ID
}

// GetDescription returns the value of Description.
func (s *UserEditReq) GetDescription() OptString {
	return s.Description
}

// GetInboundIDs returns the value of InboundIDs.
func (s *UserEditReq) GetInboundIDs() []int64 {
	return s.InboundIDs
}

// SetID sets the value of ID.
func (s *UserEditReq) SetID(val int64) {
	s.ID = val
}

// SetDescription sets the value of Description.
func (s *UserEditReq) SetDescription(val OptString) {
	s.Description = val
}

// SetInboundIDs sets the value of InboundIDs.
func (s *UserEditReq) SetInboundIDs(val []int64) {
	s.InboundIDs = val
}

type UserEditUnauthorized ErrorResponse

func (*UserEditUnauthorized) userEditRes() {}

type UserRecreateBadRequest ErrorResponse

func (*UserRecreateBadRequest) userRecreateRes() {}

type UserRecreateReq struct {
	ID int64 `json:"id"`
}

// GetID returns the value of ID.
func (s *UserRecreateReq) GetID() int64 {
	return s.ID
}

// SetID sets the value of ID.
func (s *UserRecreateReq) SetID(val int64) {
	s.ID = val
}

type UserRecreateUnauthorized ErrorResponse

func (*UserRecreateUnauthorized) userRecreateRes() {}

type UsersGetOK struct {
	Users   []UsersGetOKUsersItem `json:"users"`
	Total   int64                 `json:"total"`
	Page    int                   `json:"page"`
	PerPage int                   `json:"perPage"`
}

// GetUsers returns the value of Users.
func (s *UsersGetOK) GetUsers() []UsersGetOKUsersItem {
	return s.Users
}

// GetTotal returns the value of Total.
func (s *UsersGetOK) GetTotal() int64 {
	return s.Total
}

// GetPage returns the value of Page.
func (s *UsersGetOK) GetPage() int {
	return s.Page
}

// GetPerPage returns the value of PerPage.
func (s *UsersGetOK) GetPerPage() int {
	return s.PerPage
}

// SetUsers sets the value of Users.
func (s *UsersGetOK) SetUsers(val []UsersGetOKUsersItem) {
	s.Users = val
}

// SetTotal sets the value of Total.
func (s *UsersGetOK) SetTotal(val int64) {
	s.Total = val
}

// SetPage sets the value of Page.
func (s *UsersGetOK) SetPage(val int) {
	s.Page = val
}

// SetPerPage sets the value of PerPage.
func (s *UsersGetOK) SetPerPage(val int) {
	s.PerPage = val
}

func (*UsersGetOK) usersGetRes() {}

type UsersGetOKUsersItem struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	// Optional free-text note, shown only in the admin UI; omitted when unset.
	Description OptString `json:"description"`
	// Subscription presentation: the ordered, copyable links for this user — the raw subscription URL
	// plus app deeplinks that embed it. Titles and which links exist are decided by the backend; the UI
	// renders the list verbatim and hardcodes neither.
	Sub      UsersGetOKUsersItemSub            `json:"sub"`
	Inbounds []UsersGetOKUsersItemInboundsItem `json:"inbounds"`
	Stats    UsersGetOKUsersItemStats          `json:"stats"`
}

// GetID returns the value of ID.
func (s *UsersGetOKUsersItem) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *UsersGetOKUsersItem) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *UsersGetOKUsersItem) GetDescription() OptString {
	return s.Description
}

// GetSub returns the value of Sub.
func (s *UsersGetOKUsersItem) GetSub() UsersGetOKUsersItemSub {
	return s.Sub
}

// GetInbounds returns the value of Inbounds.
func (s *UsersGetOKUsersItem) GetInbounds() []UsersGetOKUsersItemInboundsItem {
	return s.Inbounds
}

// GetStats returns the value of Stats.
func (s *UsersGetOKUsersItem) GetStats() UsersGetOKUsersItemStats {
	return s.Stats
}

// SetID sets the value of ID.
func (s *UsersGetOKUsersItem) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *UsersGetOKUsersItem) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *UsersGetOKUsersItem) SetDescription(val OptString) {
	s.Description = val
}

// SetSub sets the value of Sub.
func (s *UsersGetOKUsersItem) SetSub(val UsersGetOKUsersItemSub) {
	s.Sub = val
}

// SetInbounds sets the value of Inbounds.
func (s *UsersGetOKUsersItem) SetInbounds(val []UsersGetOKUsersItemInboundsItem) {
	s.Inbounds = val
}

// SetStats sets the value of Stats.
func (s *UsersGetOKUsersItem) SetStats(val UsersGetOKUsersItemStats) {
	s.Stats = val
}

type UsersGetOKUsersItemInboundsItem struct {
	ID      int64  `json:"id"`
	Label   string `json:"label"`
	Port    int    `json:"port"`
	Missing bool   `json:"missing"`
}

// GetID returns the value of ID.
func (s *UsersGetOKUsersItemInboundsItem) GetID() int64 {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *UsersGetOKUsersItemInboundsItem) GetLabel() string {
	return s.Label
}

// GetPort returns the value of Port.
func (s *UsersGetOKUsersItemInboundsItem) GetPort() int {
	return s.Port
}

// GetMissing returns the value of Missing.
func (s *UsersGetOKUsersItemInboundsItem) GetMissing() bool {
	return s.Missing
}

// SetID sets the value of ID.
func (s *UsersGetOKUsersItemInboundsItem) SetID(val int64) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *UsersGetOKUsersItemInboundsItem) SetLabel(val string) {
	s.Label = val
}

// SetPort sets the value of Port.
func (s *UsersGetOKUsersItemInboundsItem) SetPort(val int) {
	s.Port = val
}

// SetMissing sets the value of Missing.
func (s *UsersGetOKUsersItemInboundsItem) SetMissing(val bool) {
	s.Missing = val
}

type UsersGetOKUsersItemStats struct {
	Up   int64 `json:"up"`
	Down int64 `json:"down"`
}

// GetUp returns the value of Up.
func (s *UsersGetOKUsersItemStats) GetUp() int64 {
	return s.Up
}

// GetDown returns the value of Down.
func (s *UsersGetOKUsersItemStats) GetDown() int64 {
	return s.Down
}

// SetUp sets the value of Up.
func (s *UsersGetOKUsersItemStats) SetUp(val int64) {
	s.Up = val
}

// SetDown sets the value of Down.
func (s *UsersGetOKUsersItemStats) SetDown(val int64) {
	s.Down = val
}

// Subscription presentation: the ordered, copyable links for this user — the raw subscription URL
// plus app deeplinks that embed it. Titles and which links exist are decided by the backend; the UI
// renders the list verbatim and hardcodes neither.
type UsersGetOKUsersItemSub struct {
	Links []UsersGetOKUsersItemSubLinksItem `json:"links"`
}

// GetLinks returns the value of Links.
func (s *UsersGetOKUsersItemSub) GetLinks() []UsersGetOKUsersItemSubLinksItem {
	return s.Links
}

// SetLinks sets the value of Links.
func (s *UsersGetOKUsersItemSub) SetLinks(val []UsersGetOKUsersItemSubLinksItem) {
	s.Links = val
}

type UsersGetOKUsersItemSubLinksItem struct {
	Title string `json:"title"`
	Value string `json:"value"`
}

// GetTitle returns the value of Title.
func (s *UsersGetOKUsersItemSubLinksItem) GetTitle() string {
	return s.Title
}

// GetValue returns the value of Value.
func (s *UsersGetOKUsersItemSubLinksItem) GetValue() string {
	return s.Value
}

// SetTitle sets the value of Title.
func (s *UsersGetOKUsersItemSubLinksItem) SetTitle(val string) {
	s.Title = val
}

// SetValue sets the value of Value.
func (s *UsersGetOKUsersItemSubLinksItem) SetValue(val string) {
	s.Value = val
}
