// Code generated by ogen, DO NOT EDIT.

package oas

// setDefaults set default value of fields.
func (s *NodeSaveReqInboundsItem) setDefaults() {
	{
		val := NodeSaveReqInboundsItemKind("vless")
		s.Kind.SetTo(val)
	}
}
