// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	AdminShellOperation     OperationName = "AdminShell"
	AdminShellViewOperation OperationName = "AdminShellView"
	ConfigCustomsOperation  OperationName = "ConfigCustoms"
	ConfigGetOperation      OperationName = "ConfigGet"
	ConfigSaveOperation     OperationName = "ConfigSave"
	ConfigSchemaOperation   OperationName = "ConfigSchema"
	CustomCreateOperation   OperationName = "CustomCreate"
	CustomDeleteOperation   OperationName = "CustomDelete"
	HealthzOperation        OperationName = "Healthz"
	LoginOperation          OperationName = "Login"
	LoginPageOperation      OperationName = "LoginPage"
	LogoutOperation         OperationName = "Logout"
	NodeDeleteOperation     OperationName = "NodeDelete"
	NodeSaveOperation       OperationName = "NodeSave"
	NodesGetOperation       OperationName = "NodesGet"
	ProviderCheckOperation  OperationName = "ProviderCheck"
	RulesOperation          OperationName = "Rules"
	SubOperation            OperationName = "Sub"
	SubProxiesOperation     OperationName = "SubProxies"
	SubRulesOperation       OperationName = "SubRules"
	UserCreateOperation     OperationName = "UserCreate"
	UserDeleteOperation     OperationName = "UserDelete"
	UserEditOperation       OperationName = "UserEdit"
	UserRecreateOperation   OperationName = "UserRecreate"
	UsersGetOperation       OperationName = "UsersGet"
)
