// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// AdminShell invokes adminShell operation.
	//
	// Admin SPA shell (HTML).
	//
	// GET /admin
	AdminShell(ctx context.Context, params AdminShellParams) (AdminShellRes, error)
	// AdminShellView invokes adminShellView operation.
	//
	// Admin SPA shell for a client-side view (HTML).
	//
	// GET /admin/{view}
	AdminShellView(ctx context.Context, params AdminShellViewParams) (AdminShellViewRes, error)
	// ConfigCustoms invokes configCustoms operation.
	//
	// Custom-config owners + the full user list.
	//
	// GET /admin/api/config/mihomo/customs
	ConfigCustoms(ctx context.Context) (ConfigCustomsRes, error)
	// ConfigGet invokes configGet operation.
	//
	// Read the mihomo config (base or a user's custom).
	//
	// GET /admin/api/config/mihomo
	ConfigGet(ctx context.Context, params ConfigGetParams) (ConfigGetRes, error)
	// ConfigSave invokes configSave operation.
	//
	// Save the mihomo config.
	//
	// POST /admin/api/config/mihomo/save
	ConfigSave(ctx context.Context, request *ConfigSaveReq) (ConfigSaveRes, error)
	// ConfigSchema invokes configSchema operation.
	//
	// The mihomo config UI schema (catalogs).
	//
	// GET /admin/api/config/mihomo/schema
	ConfigSchema(ctx context.Context) (ConfigSchemaRes, error)
	// CustomCreate invokes customCreate operation.
	//
	// Create a user's custom config (clone of base).
	//
	// POST /admin/api/config/mihomo/custom/create
	CustomCreate(ctx context.Context, request *CustomCreateReq) (CustomCreateRes, error)
	// CustomDelete invokes customDelete operation.
	//
	// Delete a user's custom config.
	//
	// POST /admin/api/config/mihomo/custom/delete
	CustomDelete(ctx context.Context, request *CustomDeleteReq) (CustomDeleteRes, error)
	// Healthz invokes healthz operation.
	//
	// Liveness probe.
	//
	// GET /healthz
	Healthz(ctx context.Context) (HealthzOK, error)
	// Login invokes login operation.
	//
	// Admin sign-in.
	//
	// POST /admin/api/login
	Login(ctx context.Context, request *LoginReq) (LoginRes, error)
	// LoginPage invokes loginPage operation.
	//
	// Admin login page (HTML).
	//
	// GET /admin/login
	LoginPage(ctx context.Context, params LoginPageParams) (LoginPageRes, error)
	// Logout invokes logout operation.
	//
	// Admin sign-out.
	//
	// POST /admin/api/logout
	Logout(ctx context.Context) (*LogoutNoContent, error)
	// NodeDelete invokes nodeDelete operation.
	//
	// Delete a node.
	//
	// POST /admin/api/nodes/delete
	NodeDelete(ctx context.Context, request *NodeDeleteReq) (NodeDeleteRes, error)
	// NodeSave invokes nodeSave operation.
	//
	// Create or update a node.
	//
	// POST /admin/api/nodes/save
	NodeSave(ctx context.Context, request *NodeSaveReq) (NodeSaveRes, error)
	// NodesGet invokes nodesGet operation.
	//
	// List nodes.
	//
	// GET /admin/api/nodes
	NodesGet(ctx context.Context) (NodesGetRes, error)
	// ProviderCheck invokes providerCheck operation.
	//
	// Probe a rule-provider URL.
	//
	// POST /admin/api/config/mihomo/provider/check
	ProviderCheck(ctx context.Context, request *ProviderCheckReq) (ProviderCheckRes, error)
	// Rules invokes rules operation.
	//
	// Fetch a mirrored rule-provider file.
	//
	// GET /rules/{file}
	Rules(ctx context.Context, params RulesParams) (RulesRes, error)
	// Sub invokes sub operation.
	//
	// Fetch a client subscription (engine YAML).
	//
	// GET /sub/{kind}/{token}
	Sub(ctx context.Context, params SubParams) (SubRes, error)
	// SubProxies invokes subProxies operation.
	//
	// Fetch a client's node list (proxy-provider payload).
	//
	// GET /sub/{kind}/{token}/proxies
	SubProxies(ctx context.Context, params SubProxiesParams) (SubProxiesRes, error)
	// SubRules invokes subRules operation.
	//
	// Fetch an authored rule-provider's list (classical text).
	//
	// GET /sub/{kind}/{token}/rules/{name}
	SubRules(ctx context.Context, params SubRulesParams) (SubRulesRes, error)
	// UserCreate invokes userCreate operation.
	//
	// Create a user.
	//
	// POST /admin/api/users/create
	UserCreate(ctx context.Context, request *UserCreateReq) (UserCreateRes, error)
	// UserDelete invokes userDelete operation.
	//
	// Delete a user.
	//
	// POST /admin/api/users/delete
	UserDelete(ctx context.Context, request *UserDeleteReq) (UserDeleteRes, error)
	// UserEdit invokes userEdit operation.
	//
	// Edit a user's inbound bindings.
	//
	// POST /admin/api/users/edit
	UserEdit(ctx context.Context, request *UserEditReq) (UserEditRes, error)
	// UserRecreate invokes userRecreate operation.
	//
	// Recreate a user's panel clients.
	//
	// POST /admin/api/users/recreate
	UserRecreate(ctx context.Context, request *UserRecreateReq) (UserRecreateRes, error)
	// UsersGet invokes usersGet operation.
	//
	// List users (paged, searchable, filterable).
	//
	// GET /admin/api/users
	UsersGet(ctx context.Context, params UsersGetParams) (UsersGetRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// AdminShell invokes adminShell operation.
//
// Admin SPA shell (HTML).
//
// GET /admin
func (c *Client) AdminShell(ctx context.Context, params AdminShellParams) (AdminShellRes, error) {
	res, err := c.sendAdminShell(ctx, params)
	return res, err
}

func (c *Client) sendAdminShell(ctx context.Context, params AdminShellParams) (res AdminShellRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	cookie := uri.NewCookieEncoder(r)
	{
		// Encode "subgen_admin" parameter.
		cfg := uri.CookieParameterEncodingConfig{
			Name:    "subgen_admin",
			Explode: true,
		}

		if err := cookie.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.SubgenAdmin.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode cookie")
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeAdminShellResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// AdminShellView invokes adminShellView operation.
//
// Admin SPA shell for a client-side view (HTML).
//
// GET /admin/{view}
func (c *Client) AdminShellView(ctx context.Context, params AdminShellViewParams) (AdminShellViewRes, error) {
	res, err := c.sendAdminShellView(ctx, params)
	return res, err
}

func (c *Client) sendAdminShellView(ctx context.Context, params AdminShellViewParams) (res AdminShellViewRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/admin/"
	{
		// Encode "view" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "view",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.View))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	cookie := uri.NewCookieEncoder(r)
	{
		// Encode "subgen_admin" parameter.
		cfg := uri.CookieParameterEncodingConfig{
			Name:    "subgen_admin",
			Explode: true,
		}

		if err := cookie.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.SubgenAdmin.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode cookie")
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeAdminShellViewResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ConfigCustoms invokes configCustoms operation.
//
// Custom-config owners + the full user list.
//
// GET /admin/api/config/mihomo/customs
func (c *Client) ConfigCustoms(ctx context.Context) (ConfigCustomsRes, error) {
	res, err := c.sendConfigCustoms(ctx)
	return res, err
}

func (c *Client) sendConfigCustoms(ctx context.Context) (res ConfigCustomsRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/config/mihomo/customs"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, ConfigCustomsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeConfigCustomsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ConfigGet invokes configGet operation.
//
// Read the mihomo config (base or a user's custom).
//
// GET /admin/api/config/mihomo
func (c *Client) ConfigGet(ctx context.Context, params ConfigGetParams) (ConfigGetRes, error) {
	res, err := c.sendConfigGet(ctx, params)
	return res, err
}

func (c *Client) sendConfigGet(ctx context.Context, params ConfigGetParams) (res ConfigGetRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/config/mihomo"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "user" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "user",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.User.Get(); ok {
				return e.EncodeValue(conv.Int64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, ConfigGetOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeConfigGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ConfigSave invokes configSave operation.
//
// Save the mihomo config.
//
// POST /admin/api/config/mihomo/save
func (c *Client) ConfigSave(ctx context.Context, request *ConfigSaveReq) (ConfigSaveRes, error) {
	res, err := c.sendConfigSave(ctx, request)
	return res, err
}

func (c *Client) sendConfigSave(ctx context.Context, request *ConfigSaveReq) (res ConfigSaveRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/config/mihomo/save"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeConfigSaveRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, ConfigSaveOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeConfigSaveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ConfigSchema invokes configSchema operation.
//
// The mihomo config UI schema (catalogs).
//
// GET /admin/api/config/mihomo/schema
func (c *Client) ConfigSchema(ctx context.Context) (ConfigSchemaRes, error) {
	res, err := c.sendConfigSchema(ctx)
	return res, err
}

func (c *Client) sendConfigSchema(ctx context.Context) (res ConfigSchemaRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/config/mihomo/schema"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, ConfigSchemaOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeConfigSchemaResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CustomCreate invokes customCreate operation.
//
// Create a user's custom config (clone of base).
//
// POST /admin/api/config/mihomo/custom/create
func (c *Client) CustomCreate(ctx context.Context, request *CustomCreateReq) (CustomCreateRes, error) {
	res, err := c.sendCustomCreate(ctx, request)
	return res, err
}

func (c *Client) sendCustomCreate(ctx context.Context, request *CustomCreateReq) (res CustomCreateRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/config/mihomo/custom/create"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCustomCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, CustomCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeCustomCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CustomDelete invokes customDelete operation.
//
// Delete a user's custom config.
//
// POST /admin/api/config/mihomo/custom/delete
func (c *Client) CustomDelete(ctx context.Context, request *CustomDeleteReq) (CustomDeleteRes, error) {
	res, err := c.sendCustomDelete(ctx, request)
	return res, err
}

func (c *Client) sendCustomDelete(ctx context.Context, request *CustomDeleteReq) (res CustomDeleteRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/config/mihomo/custom/delete"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCustomDeleteRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, CustomDeleteOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeCustomDeleteResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// Healthz invokes healthz operation.
//
// Liveness probe.
//
// GET /healthz
func (c *Client) Healthz(ctx context.Context) (HealthzOK, error) {
	res, err := c.sendHealthz(ctx)
	return res, err
}

func (c *Client) sendHealthz(ctx context.Context) (res HealthzOK, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/healthz"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeHealthzResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// Login invokes login operation.
//
// Admin sign-in.
//
// POST /admin/api/login
func (c *Client) Login(ctx context.Context, request *LoginReq) (LoginRes, error) {
	res, err := c.sendLogin(ctx, request)
	return res, err
}

func (c *Client) sendLogin(ctx context.Context, request *LoginReq) (res LoginRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/login"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeLoginRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeLoginResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// LoginPage invokes loginPage operation.
//
// Admin login page (HTML).
//
// GET /admin/login
func (c *Client) LoginPage(ctx context.Context, params LoginPageParams) (LoginPageRes, error) {
	res, err := c.sendLoginPage(ctx, params)
	return res, err
}

func (c *Client) sendLoginPage(ctx context.Context, params LoginPageParams) (res LoginPageRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/login"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	cookie := uri.NewCookieEncoder(r)
	{
		// Encode "subgen_admin" parameter.
		cfg := uri.CookieParameterEncodingConfig{
			Name:    "subgen_admin",
			Explode: true,
		}

		if err := cookie.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.SubgenAdmin.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode cookie")
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeLoginPageResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// Logout invokes logout operation.
//
// Admin sign-out.
//
// POST /admin/api/logout
func (c *Client) Logout(ctx context.Context) (*LogoutNoContent, error) {
	res, err := c.sendLogout(ctx)
	return res, err
}

func (c *Client) sendLogout(ctx context.Context) (res *LogoutNoContent, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/logout"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeLogoutResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// NodeDelete invokes nodeDelete operation.
//
// Delete a node.
//
// POST /admin/api/nodes/delete
func (c *Client) NodeDelete(ctx context.Context, request *NodeDeleteReq) (NodeDeleteRes, error) {
	res, err := c.sendNodeDelete(ctx, request)
	return res, err
}

func (c *Client) sendNodeDelete(ctx context.Context, request *NodeDeleteReq) (res NodeDeleteRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/nodes/delete"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeNodeDeleteRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, NodeDeleteOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeNodeDeleteResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// NodeSave invokes nodeSave operation.
//
// Create or update a node.
//
// POST /admin/api/nodes/save
func (c *Client) NodeSave(ctx context.Context, request *NodeSaveReq) (NodeSaveRes, error) {
	res, err := c.sendNodeSave(ctx, request)
	return res, err
}

func (c *Client) sendNodeSave(ctx context.Context, request *NodeSaveReq) (res NodeSaveRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/nodes/save"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeNodeSaveRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, NodeSaveOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeNodeSaveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// NodesGet invokes nodesGet operation.
//
// List nodes.
//
// GET /admin/api/nodes
func (c *Client) NodesGet(ctx context.Context) (NodesGetRes, error) {
	res, err := c.sendNodesGet(ctx)
	return res, err
}

func (c *Client) sendNodesGet(ctx context.Context) (res NodesGetRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/nodes"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, NodesGetOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeNodesGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ProviderCheck invokes providerCheck operation.
//
// Probe a rule-provider URL.
//
// POST /admin/api/config/mihomo/provider/check
func (c *Client) ProviderCheck(ctx context.Context, request *ProviderCheckReq) (ProviderCheckRes, error) {
	res, err := c.sendProviderCheck(ctx, request)
	return res, err
}

func (c *Client) sendProviderCheck(ctx context.Context, request *ProviderCheckReq) (res ProviderCheckRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/config/mihomo/provider/check"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeProviderCheckRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, ProviderCheckOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeProviderCheckResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// Rules invokes rules operation.
//
// Fetch a mirrored rule-provider file.
//
// GET /rules/{file}
func (c *Client) Rules(ctx context.Context, params RulesParams) (RulesRes, error) {
	res, err := c.sendRules(ctx, params)
	return res, err
}

func (c *Client) sendRules(ctx context.Context, params RulesParams) (res RulesRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/rules/"
	{
		// Encode "file" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "file",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.File))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeRulesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// Sub invokes sub operation.
//
// Fetch a client subscription (engine YAML).
//
// GET /sub/{kind}/{token}
func (c *Client) Sub(ctx context.Context, params SubParams) (SubRes, error) {
	res, err := c.sendSub(ctx, params)
	return res, err
}

func (c *Client) sendSub(ctx context.Context, params SubParams) (res SubRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/sub/"
	{
		// Encode "kind" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "kind",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Kind))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/"
	{
		// Encode "token" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "token",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Token))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSubResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SubProxies invokes subProxies operation.
//
// Fetch a client's node list (proxy-provider payload).
//
// GET /sub/{kind}/{token}/proxies
func (c *Client) SubProxies(ctx context.Context, params SubProxiesParams) (SubProxiesRes, error) {
	res, err := c.sendSubProxies(ctx, params)
	return res, err
}

func (c *Client) sendSubProxies(ctx context.Context, params SubProxiesParams) (res SubProxiesRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [5]string
	pathParts[0] = "/sub/"
	{
		// Encode "kind" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "kind",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Kind))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/"
	{
		// Encode "token" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "token",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Token))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/proxies"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSubProxiesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SubRules invokes subRules operation.
//
// Fetch an authored rule-provider's list (classical text).
//
// GET /sub/{kind}/{token}/rules/{name}
func (c *Client) SubRules(ctx context.Context, params SubRulesParams) (SubRulesRes, error) {
	res, err := c.sendSubRules(ctx, params)
	return res, err
}

func (c *Client) sendSubRules(ctx context.Context, params SubRulesParams) (res SubRulesRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [6]string
	pathParts[0] = "/sub/"
	{
		// Encode "kind" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "kind",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Kind))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/"
	{
		// Encode "token" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "token",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Token))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/rules/"
	{
		// Encode "name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Name))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[5] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSubRulesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UserCreate invokes userCreate operation.
//
// Create a user.
//
// POST /admin/api/users/create
func (c *Client) UserCreate(ctx context.Context, request *UserCreateReq) (UserCreateRes, error) {
	res, err := c.sendUserCreate(ctx, request)
	return res, err
}

func (c *Client) sendUserCreate(ctx context.Context, request *UserCreateReq) (res UserCreateRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/users/create"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUserCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, UserCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeUserCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UserDelete invokes userDelete operation.
//
// Delete a user.
//
// POST /admin/api/users/delete
func (c *Client) UserDelete(ctx context.Context, request *UserDeleteReq) (UserDeleteRes, error) {
	res, err := c.sendUserDelete(ctx, request)
	return res, err
}

func (c *Client) sendUserDelete(ctx context.Context, request *UserDeleteReq) (res UserDeleteRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/users/delete"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUserDeleteRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, UserDeleteOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeUserDeleteResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UserEdit invokes userEdit operation.
//
// Edit a user's inbound bindings.
//
// POST /admin/api/users/edit
func (c *Client) UserEdit(ctx context.Context, request *UserEditReq) (UserEditRes, error) {
	res, err := c.sendUserEdit(ctx, request)
	return res, err
}

func (c *Client) sendUserEdit(ctx context.Context, request *UserEditReq) (res UserEditRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/users/edit"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUserEditRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, UserEditOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeUserEditResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UserRecreate invokes userRecreate operation.
//
// Recreate a user's panel clients.
//
// POST /admin/api/users/recreate
func (c *Client) UserRecreate(ctx context.Context, request *UserRecreateReq) (UserRecreateRes, error) {
	res, err := c.sendUserRecreate(ctx, request)
	return res, err
}

func (c *Client) sendUserRecreate(ctx context.Context, request *UserRecreateReq) (res UserRecreateRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/users/recreate"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUserRecreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, UserRecreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeUserRecreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UsersGet invokes usersGet operation.
//
// List users (paged, searchable, filterable).
//
// GET /admin/api/users
func (c *Client) UsersGet(ctx context.Context, params UsersGetParams) (UsersGetRes, error) {
	res, err := c.sendUsersGet(ctx, params)
	return res, err
}

func (c *Client) sendUsersGet(ctx context.Context, params UsersGetParams) (res UsersGetRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/admin/api/users"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "q" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "q",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Q.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "inbound" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "inbound",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if params.Inbound != nil {
				return e.EncodeArray(func(e uri.Encoder) error {
					for i, item := range params.Inbound {
						if err := func() error {
							return e.EncodeValue(conv.Int64ToString(item))
						}(); err != nil {
							return errors.Wrapf(err, "[%d]", i)
						}
					}
					return nil
				})
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "page" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "page",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Page.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "perPage" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "perPage",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.PerPage.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAdminSession(ctx, UsersGetOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AdminSession\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeUsersGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
