// Code generated by ogen, DO NOT EDIT.
package oas

type ConfigCustomsRes interface {
	configCustomsRes()
}

type ConfigGetRes interface {
	configGetRes()
}

type ConfigSaveRes interface {
	configSaveRes()
}

type ConfigSchemaRes interface {
	configSchemaRes()
}

type CustomCreateRes interface {
	customCreateRes()
}

type CustomDeleteRes interface {
	customDeleteRes()
}

type LoginRes interface {
	loginRes()
}

type NodeDeleteRes interface {
	nodeDeleteRes()
}

type NodeSaveRes interface {
	nodeSaveRes()
}

type NodesGetRes interface {
	nodesGetRes()
}

type ProviderCheckRes interface {
	providerCheckRes()
}

type RulesRes interface {
	rulesRes()
}

type SubRes interface {
	subRes()
}

type UserCreateRes interface {
	userCreateRes()
}

type UserDeleteRes interface {
	userDeleteRes()
}

type UserEditRes interface {
	userEditRes()
}

type UserRecreateRes interface {
	userRecreateRes()
}

type UsersGetRes interface {
	usersGetRes()
}
