// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package custom_delete
//

// Package custom_delete is a generated GoMock package.
package custom_delete

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockconfigsRepo is a mock of configsRepo interface.
type MockconfigsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockconfigsRepoMockRecorder
	isgomock struct{}
}

// MockconfigsRepoMockRecorder is the mock recorder for MockconfigsRepo.
type MockconfigsRepoMockRecorder struct {
	mock *MockconfigsRepo
}

// NewMockconfigsRepo creates a new mock instance.
func NewMockconfigsRepo(ctrl *gomock.Controller) *MockconfigsRepo {
	mock := &MockconfigsRepo{ctrl: ctrl}
	mock.recorder = &MockconfigsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigsRepo) EXPECT() *MockconfigsRepoMockRecorder {
	return m.recorder
}

// DeleteUserConfig mocks base method.
func (m *MockconfigsRepo) DeleteUserConfig(ctx context.Context, userID int64, kind entity.ConfigKind) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserConfig", ctx, userID, kind)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserConfig indicates an expected call of DeleteUserConfig.
func (mr *MockconfigsRepoMockRecorder) DeleteUserConfig(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserConfig", reflect.TypeOf((*MockconfigsRepo)(nil).DeleteUserConfig), ctx, userID, kind)
}
