// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package user_delete
//

// Package user_delete is a generated GoMock package.
package user_delete

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockdeleter is a mock of deleter interface.
type Mockdeleter struct {
	ctrl     *gomock.Controller
	recorder *MockdeleterMockRecorder
	isgomock struct{}
}

// MockdeleterMockRecorder is the mock recorder for Mockdeleter.
type MockdeleterMockRecorder struct {
	mock *Mockdeleter
}

// NewMockdeleter creates a new mock instance.
func NewMockdeleter(ctrl *gomock.Controller) *Mockdeleter {
	mock := &Mockdeleter{ctrl: ctrl}
	mock.recorder = &MockdeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdeleter) EXPECT() *MockdeleterMockRecorder {
	return m.recorder
}

// DeleteUser mocks base method.
func (m *Mockdeleter) DeleteUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockdeleterMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*Mockdeleter)(nil).DeleteUser), ctx, id)
}
