// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package node_delete
//

// Package node_delete is a generated GoMock package.
package node_delete

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocknodeDeleter is a mock of nodeDeleter interface.
type MocknodeDeleter struct {
	ctrl     *gomock.Controller
	recorder *MocknodeDeleterMockRecorder
	isgomock struct{}
}

// MocknodeDeleterMockRecorder is the mock recorder for MocknodeDeleter.
type MocknodeDeleterMockRecorder struct {
	mock *MocknodeDeleter
}

// NewMocknodeDeleter creates a new mock instance.
func NewMocknodeDeleter(ctrl *gomock.Controller) *MocknodeDeleter {
	mock := &MocknodeDeleter{ctrl: ctrl}
	mock.recorder = &MocknodeDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodeDeleter) EXPECT() *MocknodeDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MocknodeDeleter) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocknodeDeleterMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocknodeDeleter)(nil).Delete), ctx, id)
}
