// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package node_delete
//

// Package node_delete is a generated GoMock package.
package node_delete

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocknodesService is a mock of nodesService interface.
type MocknodesService struct {
	ctrl     *gomock.Controller
	recorder *MocknodesServiceMockRecorder
	isgomock struct{}
}

// MocknodesServiceMockRecorder is the mock recorder for MocknodesService.
type MocknodesServiceMockRecorder struct {
	mock *MocknodesService
}

// NewMocknodesService creates a new mock instance.
func NewMocknodesService(ctrl *gomock.Controller) *MocknodesService {
	mock := &MocknodesService{ctrl: ctrl}
	mock.recorder = &MocknodesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodesService) EXPECT() *MocknodesServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MocknodesService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocknodesServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocknodesService)(nil).Delete), ctx, id)
}
