// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package nodes_api
//

// Package nodes_api is a generated GoMock package.
package nodes_api

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocknodeLister is a mock of nodeLister interface.
type MocknodeLister struct {
	ctrl     *gomock.Controller
	recorder *MocknodeListerMockRecorder
	isgomock struct{}
}

// MocknodeListerMockRecorder is the mock recorder for MocknodeLister.
type MocknodeListerMockRecorder struct {
	mock *MocknodeLister
}

// NewMocknodeLister creates a new mock instance.
func NewMocknodeLister(ctrl *gomock.Controller) *MocknodeLister {
	mock := &MocknodeLister{ctrl: ctrl}
	mock.recorder = &MocknodeListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodeLister) EXPECT() *MocknodeListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MocknodeLister) List(ctx context.Context) ([]entity.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocknodeListerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocknodeLister)(nil).List), ctx)
}
