// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package provider_check
//

// Package provider_check is a generated GoMock package.
package provider_check

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockrulesetChecker is a mock of rulesetChecker interface.
type MockrulesetChecker struct {
	ctrl     *gomock.Controller
	recorder *MockrulesetCheckerMockRecorder
	isgomock struct{}
}

// MockrulesetCheckerMockRecorder is the mock recorder for MockrulesetChecker.
type MockrulesetCheckerMockRecorder struct {
	mock *MockrulesetChecker
}

// NewMockrulesetChecker creates a new mock instance.
func NewMockrulesetChecker(ctrl *gomock.Controller) *MockrulesetChecker {
	mock := &MockrulesetChecker{ctrl: ctrl}
	mock.recorder = &MockrulesetCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrulesetChecker) EXPECT() *MockrulesetCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockrulesetChecker) Check(ctx context.Context, url, format string) entity.RulesetCheckResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, url, format)
	ret0, _ := ret[0].(entity.RulesetCheckResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockrulesetCheckerMockRecorder) Check(ctx, url, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockrulesetChecker)(nil).Check), ctx, url, format)
}
