// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package provider_check
//

// Package provider_check is a generated GoMock package.
package provider_check

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockproviderChecker is a mock of providerChecker interface.
type MockproviderChecker struct {
	ctrl     *gomock.Controller
	recorder *MockproviderCheckerMockRecorder
	isgomock struct{}
}

// MockproviderCheckerMockRecorder is the mock recorder for MockproviderChecker.
type MockproviderCheckerMockRecorder struct {
	mock *MockproviderChecker
}

// NewMockproviderChecker creates a new mock instance.
func NewMockproviderChecker(ctrl *gomock.Controller) *MockproviderChecker {
	mock := &MockproviderChecker{ctrl: ctrl}
	mock.recorder = &MockproviderCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproviderChecker) EXPECT() *MockproviderCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockproviderChecker) Check(ctx context.Context, url, format string) entity.RulesetCheckResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, url, format)
	ret0, _ := ret[0].(entity.RulesetCheckResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockproviderCheckerMockRecorder) Check(ctx, url, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockproviderChecker)(nil).Check), ctx, url, format)
}
