// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package user_recreate
//

// Package user_recreate is a generated GoMock package.
package user_recreate

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockrecreator is a mock of recreator interface.
type Mockrecreator struct {
	ctrl     *gomock.Controller
	recorder *MockrecreatorMockRecorder
	isgomock struct{}
}

// MockrecreatorMockRecorder is the mock recorder for Mockrecreator.
type MockrecreatorMockRecorder struct {
	mock *Mockrecreator
}

// NewMockrecreator creates a new mock instance.
func NewMockrecreator(ctrl *gomock.Controller) *Mockrecreator {
	mock := &Mockrecreator{ctrl: ctrl}
	mock.recorder = &MockrecreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrecreator) EXPECT() *MockrecreatorMockRecorder {
	return m.recorder
}

// RecreateUser mocks base method.
func (m *Mockrecreator) RecreateUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecreateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecreateUser indicates an expected call of RecreateUser.
func (mr *MockrecreatorMockRecorder) RecreateUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecreateUser", reflect.TypeOf((*Mockrecreator)(nil).RecreateUser), ctx, id)
}
