// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package user_recreate
//

// Package user_recreate is a generated GoMock package.
package user_recreate

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockprovisioningService is a mock of provisioningService interface.
type MockprovisioningService struct {
	ctrl     *gomock.Controller
	recorder *MockprovisioningServiceMockRecorder
	isgomock struct{}
}

// MockprovisioningServiceMockRecorder is the mock recorder for MockprovisioningService.
type MockprovisioningServiceMockRecorder struct {
	mock *MockprovisioningService
}

// NewMockprovisioningService creates a new mock instance.
func NewMockprovisioningService(ctrl *gomock.Controller) *MockprovisioningService {
	mock := &MockprovisioningService{ctrl: ctrl}
	mock.recorder = &MockprovisioningServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprovisioningService) EXPECT() *MockprovisioningServiceMockRecorder {
	return m.recorder
}

// RecreateUser mocks base method.
func (m *MockprovisioningService) RecreateUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecreateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecreateUser indicates an expected call of RecreateUser.
func (mr *MockprovisioningServiceMockRecorder) RecreateUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecreateUser", reflect.TypeOf((*MockprovisioningService)(nil).RecreateUser), ctx, id)
}
