// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package fleet
//

// Package fleet is a generated GoMock package.
package fleet

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocknodeLister is a mock of nodeLister interface.
type MocknodeLister struct {
	ctrl     *gomock.Controller
	recorder *MocknodeListerMockRecorder
	isgomock struct{}
}

// MocknodeListerMockRecorder is the mock recorder for MocknodeLister.
type MocknodeListerMockRecorder struct {
	mock *MocknodeLister
}

// NewMocknodeLister creates a new mock instance.
func NewMocknodeLister(ctrl *gomock.Controller) *MocknodeLister {
	mock := &MocknodeLister{ctrl: ctrl}
	mock.recorder = &MocknodeListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodeLister) EXPECT() *MocknodeListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MocknodeLister) List(ctx context.Context) ([]entity.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocknodeListerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocknodeLister)(nil).List), ctx)
}

// MockpanelClient is a mock of panelClient interface.
type MockpanelClient struct {
	ctrl     *gomock.Controller
	recorder *MockpanelClientMockRecorder
	isgomock struct{}
}

// MockpanelClientMockRecorder is the mock recorder for MockpanelClient.
type MockpanelClientMockRecorder struct {
	mock *MockpanelClient
}

// NewMockpanelClient creates a new mock instance.
func NewMockpanelClient(ctrl *gomock.Controller) *MockpanelClient {
	mock := &MockpanelClient{ctrl: ctrl}
	mock.recorder = &MockpanelClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpanelClient) EXPECT() *MockpanelClientMockRecorder {
	return m.recorder
}

// ListInbounds mocks base method.
func (m *MockpanelClient) ListInbounds(ctx context.Context, t entity.PanelTarget) ([]entity.PanelInbound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInbounds", ctx, t)
	ret0, _ := ret[0].([]entity.PanelInbound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInbounds indicates an expected call of ListInbounds.
func (mr *MockpanelClientMockRecorder) ListInbounds(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInbounds", reflect.TypeOf((*MockpanelClient)(nil).ListInbounds), ctx, t)
}
