// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package sublinks
//

// Package sublinks is a generated GoMock package.
package sublinks

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	mihomo "github.com/postlog/subgen/internal/mihomo"
	gomock "go.uber.org/mock/gomock"
)

// MockconfigResolver is a mock of configResolver interface.
type MockconfigResolver struct {
	ctrl     *gomock.Controller
	recorder *MockconfigResolverMockRecorder
	isgomock struct{}
}

// MockconfigResolverMockRecorder is the mock recorder for MockconfigResolver.
type MockconfigResolverMockRecorder struct {
	mock *MockconfigResolver
}

// NewMockconfigResolver creates a new mock instance.
func NewMockconfigResolver(ctrl *gomock.Controller) *MockconfigResolver {
	mock := &MockconfigResolver{ctrl: ctrl}
	mock.recorder = &MockconfigResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigResolver) EXPECT() *MockconfigResolverMockRecorder {
	return m.recorder
}

// BaseConfigID mocks base method.
func (m *MockconfigResolver) BaseConfigID(ctx context.Context, kind entity.ConfigKind) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseConfigID", ctx, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BaseConfigID indicates an expected call of BaseConfigID.
func (mr *MockconfigResolverMockRecorder) BaseConfigID(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseConfigID", reflect.TypeOf((*MockconfigResolver)(nil).BaseConfigID), ctx, kind)
}

// UserConfigID mocks base method.
func (m *MockconfigResolver) UserConfigID(ctx context.Context, userID int64, kind entity.ConfigKind) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfigID", ctx, userID, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UserConfigID indicates an expected call of UserConfigID.
func (mr *MockconfigResolverMockRecorder) UserConfigID(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfigID", reflect.TypeOf((*MockconfigResolver)(nil).UserConfigID), ctx, userID, kind)
}

// UserConfigUserIDs mocks base method.
func (m *MockconfigResolver) UserConfigUserIDs(ctx context.Context, kind entity.ConfigKind) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfigUserIDs", ctx, kind)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserConfigUserIDs indicates an expected call of UserConfigUserIDs.
func (mr *MockconfigResolverMockRecorder) UserConfigUserIDs(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfigUserIDs", reflect.TypeOf((*MockconfigResolver)(nil).UserConfigUserIDs), ctx, kind)
}

// MockprofileReader is a mock of profileReader interface.
type MockprofileReader struct {
	ctrl     *gomock.Controller
	recorder *MockprofileReaderMockRecorder
	isgomock struct{}
}

// MockprofileReaderMockRecorder is the mock recorder for MockprofileReader.
type MockprofileReaderMockRecorder struct {
	mock *MockprofileReader
}

// NewMockprofileReader creates a new mock instance.
func NewMockprofileReader(ctrl *gomock.Controller) *MockprofileReader {
	mock := &MockprofileReader{ctrl: ctrl}
	mock.recorder = &MockprofileReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprofileReader) EXPECT() *MockprofileReaderMockRecorder {
	return m.recorder
}

// Profile mocks base method.
func (m *MockprofileReader) Profile(ctx context.Context, configID int64) (mihomo.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile", ctx, configID)
	ret0, _ := ret[0].(mihomo.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockprofileReaderMockRecorder) Profile(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockprofileReader)(nil).Profile), ctx, configID)
}
