// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package sublinks
//

// Package sublinks is a generated GoMock package.
package sublinks

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	mihomo "github.com/postlog/subgen/internal/mihomo"
	gomock "go.uber.org/mock/gomock"
)

// MockconfigsRepo is a mock of configsRepo interface.
type MockconfigsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockconfigsRepoMockRecorder
	isgomock struct{}
}

// MockconfigsRepoMockRecorder is the mock recorder for MockconfigsRepo.
type MockconfigsRepoMockRecorder struct {
	mock *MockconfigsRepo
}

// NewMockconfigsRepo creates a new mock instance.
func NewMockconfigsRepo(ctrl *gomock.Controller) *MockconfigsRepo {
	mock := &MockconfigsRepo{ctrl: ctrl}
	mock.recorder = &MockconfigsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigsRepo) EXPECT() *MockconfigsRepoMockRecorder {
	return m.recorder
}

// BaseConfigID mocks base method.
func (m *MockconfigsRepo) BaseConfigID(ctx context.Context, kind entity.ConfigKind) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseConfigID", ctx, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BaseConfigID indicates an expected call of BaseConfigID.
func (mr *MockconfigsRepoMockRecorder) BaseConfigID(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseConfigID", reflect.TypeOf((*MockconfigsRepo)(nil).BaseConfigID), ctx, kind)
}

// UserConfigID mocks base method.
func (m *MockconfigsRepo) UserConfigID(ctx context.Context, userID int64, kind entity.ConfigKind) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfigID", ctx, userID, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UserConfigID indicates an expected call of UserConfigID.
func (mr *MockconfigsRepoMockRecorder) UserConfigID(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfigID", reflect.TypeOf((*MockconfigsRepo)(nil).UserConfigID), ctx, userID, kind)
}

// UserConfigUserIDs mocks base method.
func (m *MockconfigsRepo) UserConfigUserIDs(ctx context.Context, kind entity.ConfigKind) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfigUserIDs", ctx, kind)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserConfigUserIDs indicates an expected call of UserConfigUserIDs.
func (mr *MockconfigsRepoMockRecorder) UserConfigUserIDs(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfigUserIDs", reflect.TypeOf((*MockconfigsRepo)(nil).UserConfigUserIDs), ctx, kind)
}

// MockroutingRepo is a mock of routingRepo interface.
type MockroutingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockroutingRepoMockRecorder
	isgomock struct{}
}

// MockroutingRepoMockRecorder is the mock recorder for MockroutingRepo.
type MockroutingRepoMockRecorder struct {
	mock *MockroutingRepo
}

// NewMockroutingRepo creates a new mock instance.
func NewMockroutingRepo(ctrl *gomock.Controller) *MockroutingRepo {
	mock := &MockroutingRepo{ctrl: ctrl}
	mock.recorder = &MockroutingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroutingRepo) EXPECT() *MockroutingRepoMockRecorder {
	return m.recorder
}

// Profile mocks base method.
func (m *MockroutingRepo) Profile(ctx context.Context, configID int64) (mihomo.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile", ctx, configID)
	ret0, _ := ret[0].(mihomo.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockroutingRepoMockRecorder) Profile(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockroutingRepo)(nil).Profile), ctx, configID)
}
