// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package sub
//

// Package sub is a generated GoMock package.
package sub

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	mihomo "github.com/postlog/subgen/internal/mihomo"
	gomock "go.uber.org/mock/gomock"
)

// MocksubIDLister is a mock of subIDLister interface.
type MocksubIDLister struct {
	ctrl     *gomock.Controller
	recorder *MocksubIDListerMockRecorder
	isgomock struct{}
}

// MocksubIDListerMockRecorder is the mock recorder for MocksubIDLister.
type MocksubIDListerMockRecorder struct {
	mock *MocksubIDLister
}

// NewMocksubIDLister creates a new mock instance.
func NewMocksubIDLister(ctrl *gomock.Controller) *MocksubIDLister {
	mock := &MocksubIDLister{ctrl: ctrl}
	mock.recorder = &MocksubIDListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubIDLister) EXPECT() *MocksubIDListerMockRecorder {
	return m.recorder
}

// SubIDs mocks base method.
func (m *MocksubIDLister) SubIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubIDs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubIDs indicates an expected call of SubIDs.
func (mr *MocksubIDListerMockRecorder) SubIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubIDs", reflect.TypeOf((*MocksubIDLister)(nil).SubIDs), ctx)
}

// MockfleetReader is a mock of fleetReader interface.
type MockfleetReader struct {
	ctrl     *gomock.Controller
	recorder *MockfleetReaderMockRecorder
	isgomock struct{}
}

// MockfleetReaderMockRecorder is the mock recorder for MockfleetReader.
type MockfleetReaderMockRecorder struct {
	mock *MockfleetReader
}

// NewMockfleetReader creates a new mock instance.
func NewMockfleetReader(ctrl *gomock.Controller) *MockfleetReader {
	mock := &MockfleetReader{ctrl: ctrl}
	mock.recorder = &MockfleetReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfleetReader) EXPECT() *MockfleetReaderMockRecorder {
	return m.recorder
}

// Fleet mocks base method.
func (m *MockfleetReader) Fleet(ctx context.Context) (*entity.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fleet", ctx)
	ret0, _ := ret[0].(*entity.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fleet indicates an expected call of Fleet.
func (mr *MockfleetReaderMockRecorder) Fleet(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fleet", reflect.TypeOf((*MockfleetReader)(nil).Fleet), ctx)
}

// MockmihomoReader is a mock of mihomoReader interface.
type MockmihomoReader struct {
	ctrl     *gomock.Controller
	recorder *MockmihomoReaderMockRecorder
	isgomock struct{}
}

// MockmihomoReaderMockRecorder is the mock recorder for MockmihomoReader.
type MockmihomoReaderMockRecorder struct {
	mock *MockmihomoReader
}

// NewMockmihomoReader creates a new mock instance.
func NewMockmihomoReader(ctrl *gomock.Controller) *MockmihomoReader {
	mock := &MockmihomoReader{ctrl: ctrl}
	mock.recorder = &MockmihomoReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmihomoReader) EXPECT() *MockmihomoReaderMockRecorder {
	return m.recorder
}

// ProxyGroups mocks base method.
func (m *MockmihomoReader) ProxyGroups(ctx context.Context) ([]mihomo.ProxyGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyGroups", ctx)
	ret0, _ := ret[0].([]mihomo.ProxyGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProxyGroups indicates an expected call of ProxyGroups.
func (mr *MockmihomoReaderMockRecorder) ProxyGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyGroups", reflect.TypeOf((*MockmihomoReader)(nil).ProxyGroups), ctx)
}

// RuleProviders mocks base method.
func (m *MockmihomoReader) RuleProviders(ctx context.Context) ([]mihomo.RuleProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RuleProviders", ctx)
	ret0, _ := ret[0].([]mihomo.RuleProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RuleProviders indicates an expected call of RuleProviders.
func (mr *MockmihomoReaderMockRecorder) RuleProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RuleProviders", reflect.TypeOf((*MockmihomoReader)(nil).RuleProviders), ctx)
}

// Rules mocks base method.
func (m *MockmihomoReader) Rules(ctx context.Context) ([]mihomo.RoutingRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rules", ctx)
	ret0, _ := ret[0].([]mihomo.RoutingRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rules indicates an expected call of Rules.
func (mr *MockmihomoReaderMockRecorder) Rules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rules", reflect.TypeOf((*MockmihomoReader)(nil).Rules), ctx)
}

// Setting mocks base method.
func (m *MockmihomoReader) Setting(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Setting", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Setting indicates an expected call of Setting.
func (mr *MockmihomoReaderMockRecorder) Setting(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setting", reflect.TypeOf((*MockmihomoReader)(nil).Setting), ctx, key)
}
