// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package sub
//

// Package sub is a generated GoMock package.
package sub

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	mihomo "github.com/postlog/subgen/internal/mihomo"
	gomock "go.uber.org/mock/gomock"
)

// MockusersRepo is a mock of usersRepo interface.
type MockusersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockusersRepoMockRecorder
	isgomock struct{}
}

// MockusersRepoMockRecorder is the mock recorder for MockusersRepo.
type MockusersRepoMockRecorder struct {
	mock *MockusersRepo
}

// NewMockusersRepo creates a new mock instance.
func NewMockusersRepo(ctrl *gomock.Controller) *MockusersRepo {
	mock := &MockusersRepo{ctrl: ctrl}
	mock.recorder = &MockusersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockusersRepo) EXPECT() *MockusersRepoMockRecorder {
	return m.recorder
}

// IDBySubID mocks base method.
func (m *MockusersRepo) IDBySubID(ctx context.Context, subID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IDBySubID", ctx, subID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IDBySubID indicates an expected call of IDBySubID.
func (mr *MockusersRepoMockRecorder) IDBySubID(ctx, subID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IDBySubID", reflect.TypeOf((*MockusersRepo)(nil).IDBySubID), ctx, subID)
}

// SubIDs mocks base method.
func (m *MockusersRepo) SubIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubIDs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubIDs indicates an expected call of SubIDs.
func (mr *MockusersRepoMockRecorder) SubIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubIDs", reflect.TypeOf((*MockusersRepo)(nil).SubIDs), ctx)
}

// MockfleetService is a mock of fleetService interface.
type MockfleetService struct {
	ctrl     *gomock.Controller
	recorder *MockfleetServiceMockRecorder
	isgomock struct{}
}

// MockfleetServiceMockRecorder is the mock recorder for MockfleetService.
type MockfleetServiceMockRecorder struct {
	mock *MockfleetService
}

// NewMockfleetService creates a new mock instance.
func NewMockfleetService(ctrl *gomock.Controller) *MockfleetService {
	mock := &MockfleetService{ctrl: ctrl}
	mock.recorder = &MockfleetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfleetService) EXPECT() *MockfleetServiceMockRecorder {
	return m.recorder
}

// Fleet mocks base method.
func (m *MockfleetService) Fleet(ctx context.Context) (*entity.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fleet", ctx)
	ret0, _ := ret[0].(*entity.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fleet indicates an expected call of Fleet.
func (mr *MockfleetServiceMockRecorder) Fleet(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fleet", reflect.TypeOf((*MockfleetService)(nil).Fleet), ctx)
}

// MockconfigsRepo is a mock of configsRepo interface.
type MockconfigsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockconfigsRepoMockRecorder
	isgomock struct{}
}

// MockconfigsRepoMockRecorder is the mock recorder for MockconfigsRepo.
type MockconfigsRepoMockRecorder struct {
	mock *MockconfigsRepo
}

// NewMockconfigsRepo creates a new mock instance.
func NewMockconfigsRepo(ctrl *gomock.Controller) *MockconfigsRepo {
	mock := &MockconfigsRepo{ctrl: ctrl}
	mock.recorder = &MockconfigsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigsRepo) EXPECT() *MockconfigsRepoMockRecorder {
	return m.recorder
}

// BaseConfigID mocks base method.
func (m *MockconfigsRepo) BaseConfigID(ctx context.Context, kind entity.ConfigKind) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseConfigID", ctx, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BaseConfigID indicates an expected call of BaseConfigID.
func (mr *MockconfigsRepoMockRecorder) BaseConfigID(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseConfigID", reflect.TypeOf((*MockconfigsRepo)(nil).BaseConfigID), ctx, kind)
}

// UserConfigID mocks base method.
func (m *MockconfigsRepo) UserConfigID(ctx context.Context, userID int64, kind entity.ConfigKind) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfigID", ctx, userID, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UserConfigID indicates an expected call of UserConfigID.
func (mr *MockconfigsRepoMockRecorder) UserConfigID(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfigID", reflect.TypeOf((*MockconfigsRepo)(nil).UserConfigID), ctx, userID, kind)
}

// MockEngineRenderer is a mock of EngineRenderer interface.
type MockEngineRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockEngineRendererMockRecorder
	isgomock struct{}
}

// MockEngineRendererMockRecorder is the mock recorder for MockEngineRenderer.
type MockEngineRendererMockRecorder struct {
	mock *MockEngineRenderer
}

// NewMockEngineRenderer creates a new mock instance.
func NewMockEngineRenderer(ctrl *gomock.Controller) *MockEngineRenderer {
	mock := &MockEngineRenderer{ctrl: ctrl}
	mock.recorder = &MockEngineRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineRenderer) EXPECT() *MockEngineRendererMockRecorder {
	return m.recorder
}

// Kind mocks base method.
func (m *MockEngineRenderer) Kind() entity.ConfigKind {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kind")
	ret0, _ := ret[0].(entity.ConfigKind)
	return ret0
}

// Kind indicates an expected call of Kind.
func (mr *MockEngineRendererMockRecorder) Kind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kind", reflect.TypeOf((*MockEngineRenderer)(nil).Kind))
}

// Render mocks base method.
func (m *MockEngineRenderer) Render(ctx context.Context, sub *entity.Subscriber, configID int64, token string) ([]byte, RenderMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx, sub, configID, token)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(RenderMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Render indicates an expected call of Render.
func (mr *MockEngineRendererMockRecorder) Render(ctx, sub, configID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockEngineRenderer)(nil).Render), ctx, sub, configID, token)
}

// RenderProxies mocks base method.
func (m *MockEngineRenderer) RenderProxies(ctx context.Context, sub *entity.Subscriber) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderProxies", ctx, sub)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderProxies indicates an expected call of RenderProxies.
func (mr *MockEngineRendererMockRecorder) RenderProxies(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderProxies", reflect.TypeOf((*MockEngineRenderer)(nil).RenderProxies), ctx, sub)
}

// RenderRuleProvider mocks base method.
func (m *MockEngineRenderer) RenderRuleProvider(ctx context.Context, configID int64, name string) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderRuleProvider", ctx, configID, name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RenderRuleProvider indicates an expected call of RenderRuleProvider.
func (mr *MockEngineRendererMockRecorder) RenderRuleProvider(ctx, configID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderRuleProvider", reflect.TypeOf((*MockEngineRenderer)(nil).RenderRuleProvider), ctx, configID, name)
}

// MockroutingRepo is a mock of routingRepo interface.
type MockroutingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockroutingRepoMockRecorder
	isgomock struct{}
}

// MockroutingRepoMockRecorder is the mock recorder for MockroutingRepo.
type MockroutingRepoMockRecorder struct {
	mock *MockroutingRepo
}

// NewMockroutingRepo creates a new mock instance.
func NewMockroutingRepo(ctrl *gomock.Controller) *MockroutingRepo {
	mock := &MockroutingRepo{ctrl: ctrl}
	mock.recorder = &MockroutingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroutingRepo) EXPECT() *MockroutingRepoMockRecorder {
	return m.recorder
}

// Profile mocks base method.
func (m *MockroutingRepo) Profile(ctx context.Context, configID int64) (mihomo.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile", ctx, configID)
	ret0, _ := ret[0].(mihomo.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockroutingRepoMockRecorder) Profile(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockroutingRepo)(nil).Profile), ctx, configID)
}

// ProxyGroups mocks base method.
func (m *MockroutingRepo) ProxyGroups(ctx context.Context, configID int64) ([]mihomo.ProxyGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyGroups", ctx, configID)
	ret0, _ := ret[0].([]mihomo.ProxyGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProxyGroups indicates an expected call of ProxyGroups.
func (mr *MockroutingRepoMockRecorder) ProxyGroups(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyGroups", reflect.TypeOf((*MockroutingRepo)(nil).ProxyGroups), ctx, configID)
}

// RuleProviders mocks base method.
func (m *MockroutingRepo) RuleProviders(ctx context.Context, configID int64) ([]mihomo.RuleProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RuleProviders", ctx, configID)
	ret0, _ := ret[0].([]mihomo.RuleProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RuleProviders indicates an expected call of RuleProviders.
func (mr *MockroutingRepoMockRecorder) RuleProviders(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RuleProviders", reflect.TypeOf((*MockroutingRepo)(nil).RuleProviders), ctx, configID)
}

// Rules mocks base method.
func (m *MockroutingRepo) Rules(ctx context.Context, configID int64) ([]mihomo.RoutingRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rules", ctx, configID)
	ret0, _ := ret[0].([]mihomo.RoutingRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rules indicates an expected call of Rules.
func (mr *MockroutingRepoMockRecorder) Rules(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rules", reflect.TypeOf((*MockroutingRepo)(nil).Rules), ctx, configID)
}

// Setting mocks base method.
func (m *MockroutingRepo) Setting(ctx context.Context, configID int64, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Setting", ctx, configID, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Setting indicates an expected call of Setting.
func (mr *MockroutingRepoMockRecorder) Setting(ctx, configID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setting", reflect.TypeOf((*MockroutingRepo)(nil).Setting), ctx, configID, key)
}
