// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package config_save
//

// Package config_save is a generated GoMock package.
package config_save

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	mihomo "github.com/postlog/subgen/internal/mihomo"
	gomock "go.uber.org/mock/gomock"
)

// MockconfigResolver is a mock of configResolver interface.
type MockconfigResolver struct {
	ctrl     *gomock.Controller
	recorder *MockconfigResolverMockRecorder
	isgomock struct{}
}

// MockconfigResolverMockRecorder is the mock recorder for MockconfigResolver.
type MockconfigResolverMockRecorder struct {
	mock *MockconfigResolver
}

// NewMockconfigResolver creates a new mock instance.
func NewMockconfigResolver(ctrl *gomock.Controller) *MockconfigResolver {
	mock := &MockconfigResolver{ctrl: ctrl}
	mock.recorder = &MockconfigResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigResolver) EXPECT() *MockconfigResolverMockRecorder {
	return m.recorder
}

// EnsureBaseConfigID mocks base method.
func (m *MockconfigResolver) EnsureBaseConfigID(ctx context.Context, kind entity.ConfigKind) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureBaseConfigID", ctx, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureBaseConfigID indicates an expected call of EnsureBaseConfigID.
func (mr *MockconfigResolverMockRecorder) EnsureBaseConfigID(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureBaseConfigID", reflect.TypeOf((*MockconfigResolver)(nil).EnsureBaseConfigID), ctx, kind)
}

// UserConfigID mocks base method.
func (m *MockconfigResolver) UserConfigID(ctx context.Context, userID int64, kind entity.ConfigKind) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfigID", ctx, userID, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UserConfigID indicates an expected call of UserConfigID.
func (mr *MockconfigResolverMockRecorder) UserConfigID(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfigID", reflect.TypeOf((*MockconfigResolver)(nil).UserConfigID), ctx, userID, kind)
}

// MockmihomoSaver is a mock of mihomoSaver interface.
type MockmihomoSaver struct {
	ctrl     *gomock.Controller
	recorder *MockmihomoSaverMockRecorder
	isgomock struct{}
}

// MockmihomoSaverMockRecorder is the mock recorder for MockmihomoSaver.
type MockmihomoSaverMockRecorder struct {
	mock *MockmihomoSaver
}

// NewMockmihomoSaver creates a new mock instance.
func NewMockmihomoSaver(ctrl *gomock.Controller) *MockmihomoSaver {
	mock := &MockmihomoSaver{ctrl: ctrl}
	mock.recorder = &MockmihomoSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmihomoSaver) EXPECT() *MockmihomoSaverMockRecorder {
	return m.recorder
}

// SaveMihomoConfig mocks base method.
func (m *MockmihomoSaver) SaveMihomoConfig(ctx context.Context, configID int64, rules []mihomo.RoutingRule, groups []mihomo.ProxyGroup, rps []mihomo.RuleProvider, baseYAML string, profile mihomo.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMihomoConfig", ctx, configID, rules, groups, rps, baseYAML, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMihomoConfig indicates an expected call of SaveMihomoConfig.
func (mr *MockmihomoSaverMockRecorder) SaveMihomoConfig(ctx, configID, rules, groups, rps, baseYAML, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMihomoConfig", reflect.TypeOf((*MockmihomoSaver)(nil).SaveMihomoConfig), ctx, configID, rules, groups, rps, baseYAML, profile)
}
