// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package config_save
//

// Package config_save is a generated GoMock package.
package config_save

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	mihomo "github.com/postlog/subgen/internal/mihomo"
	gomock "go.uber.org/mock/gomock"
)

// MockconfigsRepo is a mock of configsRepo interface.
type MockconfigsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockconfigsRepoMockRecorder
	isgomock struct{}
}

// MockconfigsRepoMockRecorder is the mock recorder for MockconfigsRepo.
type MockconfigsRepoMockRecorder struct {
	mock *MockconfigsRepo
}

// NewMockconfigsRepo creates a new mock instance.
func NewMockconfigsRepo(ctrl *gomock.Controller) *MockconfigsRepo {
	mock := &MockconfigsRepo{ctrl: ctrl}
	mock.recorder = &MockconfigsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigsRepo) EXPECT() *MockconfigsRepoMockRecorder {
	return m.recorder
}

// EnsureBaseConfigID mocks base method.
func (m *MockconfigsRepo) EnsureBaseConfigID(ctx context.Context, kind entity.ConfigKind) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureBaseConfigID", ctx, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureBaseConfigID indicates an expected call of EnsureBaseConfigID.
func (mr *MockconfigsRepoMockRecorder) EnsureBaseConfigID(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureBaseConfigID", reflect.TypeOf((*MockconfigsRepo)(nil).EnsureBaseConfigID), ctx, kind)
}

// UserConfigID mocks base method.
func (m *MockconfigsRepo) UserConfigID(ctx context.Context, userID int64, kind entity.ConfigKind) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfigID", ctx, userID, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UserConfigID indicates an expected call of UserConfigID.
func (mr *MockconfigsRepoMockRecorder) UserConfigID(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfigID", reflect.TypeOf((*MockconfigsRepo)(nil).UserConfigID), ctx, userID, kind)
}

// MockroutingRepo is a mock of routingRepo interface.
type MockroutingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockroutingRepoMockRecorder
	isgomock struct{}
}

// MockroutingRepoMockRecorder is the mock recorder for MockroutingRepo.
type MockroutingRepoMockRecorder struct {
	mock *MockroutingRepo
}

// NewMockroutingRepo creates a new mock instance.
func NewMockroutingRepo(ctrl *gomock.Controller) *MockroutingRepo {
	mock := &MockroutingRepo{ctrl: ctrl}
	mock.recorder = &MockroutingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroutingRepo) EXPECT() *MockroutingRepoMockRecorder {
	return m.recorder
}

// SaveMihomoConfig mocks base method.
func (m *MockroutingRepo) SaveMihomoConfig(ctx context.Context, configID int64, draft mihomo.ConfigDraft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMihomoConfig", ctx, configID, draft)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMihomoConfig indicates an expected call of SaveMihomoConfig.
func (mr *MockroutingRepoMockRecorder) SaveMihomoConfig(ctx, configID, draft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMihomoConfig", reflect.TypeOf((*MockroutingRepo)(nil).SaveMihomoConfig), ctx, configID, draft)
}
