// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package config_save
//

// Package config_save is a generated GoMock package.
package config_save

import (
	context "context"
	reflect "reflect"

	mihomo "github.com/postlog/subgen/internal/mihomo"
	gomock "go.uber.org/mock/gomock"
)

// MockmihomoSaver is a mock of mihomoSaver interface.
type MockmihomoSaver struct {
	ctrl     *gomock.Controller
	recorder *MockmihomoSaverMockRecorder
	isgomock struct{}
}

// MockmihomoSaverMockRecorder is the mock recorder for MockmihomoSaver.
type MockmihomoSaverMockRecorder struct {
	mock *MockmihomoSaver
}

// NewMockmihomoSaver creates a new mock instance.
func NewMockmihomoSaver(ctrl *gomock.Controller) *MockmihomoSaver {
	mock := &MockmihomoSaver{ctrl: ctrl}
	mock.recorder = &MockmihomoSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmihomoSaver) EXPECT() *MockmihomoSaverMockRecorder {
	return m.recorder
}

// SaveMihomoConfig mocks base method.
func (m *MockmihomoSaver) SaveMihomoConfig(ctx context.Context, rules []mihomo.RoutingRule, groups []mihomo.ProxyGroup, rps []mihomo.RuleProvider, baseYAML string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMihomoConfig", ctx, rules, groups, rps, baseYAML)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMihomoConfig indicates an expected call of SaveMihomoConfig.
func (mr *MockmihomoSaverMockRecorder) SaveMihomoConfig(ctx, rules, groups, rps, baseYAML any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMihomoConfig", reflect.TypeOf((*MockmihomoSaver)(nil).SaveMihomoConfig), ctx, rules, groups, rps, baseYAML)
}
