// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package rules
//

// Package rules is a generated GoMock package.
package rules

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockrulesetMirror is a mock of rulesetMirror interface.
type MockrulesetMirror struct {
	ctrl     *gomock.Controller
	recorder *MockrulesetMirrorMockRecorder
	isgomock struct{}
}

// MockrulesetMirrorMockRecorder is the mock recorder for MockrulesetMirror.
type MockrulesetMirrorMockRecorder struct {
	mock *MockrulesetMirror
}

// NewMockrulesetMirror creates a new mock instance.
func NewMockrulesetMirror(ctrl *gomock.Controller) *MockrulesetMirror {
	mock := &MockrulesetMirror{ctrl: ctrl}
	mock.recorder = &MockrulesetMirrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrulesetMirror) EXPECT() *MockrulesetMirrorMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockrulesetMirror) Get(file string) ([]byte, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", file)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockrulesetMirrorMockRecorder) Get(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockrulesetMirror)(nil).Get), file)
}
