// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package rules
//

// Package rules is a generated GoMock package.
package rules

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockruleFiles is a mock of ruleFiles interface.
type MockruleFiles struct {
	ctrl     *gomock.Controller
	recorder *MockruleFilesMockRecorder
	isgomock struct{}
}

// MockruleFilesMockRecorder is the mock recorder for MockruleFiles.
type MockruleFilesMockRecorder struct {
	mock *MockruleFiles
}

// NewMockruleFiles creates a new mock instance.
func NewMockruleFiles(ctrl *gomock.Controller) *MockruleFiles {
	mock := &MockruleFiles{ctrl: ctrl}
	mock.recorder = &MockruleFilesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockruleFiles) EXPECT() *MockruleFilesMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockruleFiles) Get(file string) ([]byte, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", file)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockruleFilesMockRecorder) Get(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockruleFiles)(nil).Get), file)
}
