// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package users_api
//

// Package users_api is a generated GoMock package.
package users_api

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockuserLister is a mock of userLister interface.
type MockuserLister struct {
	ctrl     *gomock.Controller
	recorder *MockuserListerMockRecorder
	isgomock struct{}
}

// MockuserListerMockRecorder is the mock recorder for MockuserLister.
type MockuserListerMockRecorder struct {
	mock *MockuserLister
}

// NewMockuserLister creates a new mock instance.
func NewMockuserLister(ctrl *gomock.Controller) *MockuserLister {
	mock := &MockuserLister{ctrl: ctrl}
	mock.recorder = &MockuserListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserLister) EXPECT() *MockuserListerMockRecorder {
	return m.recorder
}

// ListPage mocks base method.
func (m *MockuserLister) ListPage(ctx context.Context, p entity.UserListParams) (entity.UserPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPage", ctx, p)
	ret0, _ := ret[0].(entity.UserPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPage indicates an expected call of ListPage.
func (mr *MockuserListerMockRecorder) ListPage(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPage", reflect.TypeOf((*MockuserLister)(nil).ListPage), ctx, p)
}

// MockfleetReader is a mock of fleetReader interface.
type MockfleetReader struct {
	ctrl     *gomock.Controller
	recorder *MockfleetReaderMockRecorder
	isgomock struct{}
}

// MockfleetReaderMockRecorder is the mock recorder for MockfleetReader.
type MockfleetReaderMockRecorder struct {
	mock *MockfleetReader
}

// NewMockfleetReader creates a new mock instance.
func NewMockfleetReader(ctrl *gomock.Controller) *MockfleetReader {
	mock := &MockfleetReader{ctrl: ctrl}
	mock.recorder = &MockfleetReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfleetReader) EXPECT() *MockfleetReaderMockRecorder {
	return m.recorder
}

// Fleet mocks base method.
func (m *MockfleetReader) Fleet(ctx context.Context) (*entity.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fleet", ctx)
	ret0, _ := ret[0].(*entity.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fleet indicates an expected call of Fleet.
func (mr *MockfleetReaderMockRecorder) Fleet(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fleet", reflect.TypeOf((*MockfleetReader)(nil).Fleet), ctx)
}
