// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package users_api
//

// Package users_api is a generated GoMock package.
package users_api

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockuserLister is a mock of userLister interface.
type MockuserLister struct {
	ctrl     *gomock.Controller
	recorder *MockuserListerMockRecorder
	isgomock struct{}
}

// MockuserListerMockRecorder is the mock recorder for MockuserLister.
type MockuserListerMockRecorder struct {
	mock *MockuserLister
}

// NewMockuserLister creates a new mock instance.
func NewMockuserLister(ctrl *gomock.Controller) *MockuserLister {
	mock := &MockuserLister{ctrl: ctrl}
	mock.recorder = &MockuserListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserLister) EXPECT() *MockuserListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockuserLister) List(ctx context.Context) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockuserListerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockuserLister)(nil).List), ctx)
}

// MockfleetReader is a mock of fleetReader interface.
type MockfleetReader struct {
	ctrl     *gomock.Controller
	recorder *MockfleetReaderMockRecorder
	isgomock struct{}
}

// MockfleetReaderMockRecorder is the mock recorder for MockfleetReader.
type MockfleetReaderMockRecorder struct {
	mock *MockfleetReader
}

// NewMockfleetReader creates a new mock instance.
func NewMockfleetReader(ctrl *gomock.Controller) *MockfleetReader {
	mock := &MockfleetReader{ctrl: ctrl}
	mock.recorder = &MockfleetReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfleetReader) EXPECT() *MockfleetReaderMockRecorder {
	return m.recorder
}

// Fleet mocks base method.
func (m *MockfleetReader) Fleet(ctx context.Context) (*entity.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fleet", ctx)
	ret0, _ := ret[0].(*entity.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fleet indicates an expected call of Fleet.
func (mr *MockfleetReaderMockRecorder) Fleet(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fleet", reflect.TypeOf((*MockfleetReader)(nil).Fleet), ctx)
}

// MockconnHealth is a mock of connHealth interface.
type MockconnHealth struct {
	ctrl     *gomock.Controller
	recorder *MockconnHealthMockRecorder
	isgomock struct{}
}

// MockconnHealthMockRecorder is the mock recorder for MockconnHealth.
type MockconnHealthMockRecorder struct {
	mock *MockconnHealth
}

// NewMockconnHealth creates a new mock instance.
func NewMockconnHealth(ctrl *gomock.Controller) *MockconnHealth {
	mock := &MockconnHealth{ctrl: ctrl}
	mock.recorder = &MockconnHealthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconnHealth) EXPECT() *MockconnHealthMockRecorder {
	return m.recorder
}

// MissingConnections mocks base method.
func (m *MockconnHealth) MissingConnections(ctx context.Context, u *entity.User) []entity.Connection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MissingConnections", ctx, u)
	ret0, _ := ret[0].([]entity.Connection)
	return ret0
}

// MissingConnections indicates an expected call of MissingConnections.
func (mr *MockconnHealthMockRecorder) MissingConnections(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MissingConnections", reflect.TypeOf((*MockconnHealth)(nil).MissingConnections), ctx, u)
}
