// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package users_get
//

// Package users_get is a generated GoMock package.
package users_get

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockusersRepo is a mock of usersRepo interface.
type MockusersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockusersRepoMockRecorder
	isgomock struct{}
}

// MockusersRepoMockRecorder is the mock recorder for MockusersRepo.
type MockusersRepoMockRecorder struct {
	mock *MockusersRepo
}

// NewMockusersRepo creates a new mock instance.
func NewMockusersRepo(ctrl *gomock.Controller) *MockusersRepo {
	mock := &MockusersRepo{ctrl: ctrl}
	mock.recorder = &MockusersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockusersRepo) EXPECT() *MockusersRepoMockRecorder {
	return m.recorder
}

// ListPage mocks base method.
func (m *MockusersRepo) ListPage(ctx context.Context, p entity.UserListParams) (entity.UserPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPage", ctx, p)
	ret0, _ := ret[0].(entity.UserPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPage indicates an expected call of ListPage.
func (mr *MockusersRepoMockRecorder) ListPage(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPage", reflect.TypeOf((*MockusersRepo)(nil).ListPage), ctx, p)
}

// MockfleetService is a mock of fleetService interface.
type MockfleetService struct {
	ctrl     *gomock.Controller
	recorder *MockfleetServiceMockRecorder
	isgomock struct{}
}

// MockfleetServiceMockRecorder is the mock recorder for MockfleetService.
type MockfleetServiceMockRecorder struct {
	mock *MockfleetService
}

// NewMockfleetService creates a new mock instance.
func NewMockfleetService(ctrl *gomock.Controller) *MockfleetService {
	mock := &MockfleetService{ctrl: ctrl}
	mock.recorder = &MockfleetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfleetService) EXPECT() *MockfleetServiceMockRecorder {
	return m.recorder
}

// Fleet mocks base method.
func (m *MockfleetService) Fleet(ctx context.Context) (*entity.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fleet", ctx)
	ret0, _ := ret[0].(*entity.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fleet indicates an expected call of Fleet.
func (mr *MockfleetServiceMockRecorder) Fleet(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fleet", reflect.TypeOf((*MockfleetService)(nil).Fleet), ctx)
}

// MocksublinksService is a mock of sublinksService interface.
type MocksublinksService struct {
	ctrl     *gomock.Controller
	recorder *MocksublinksServiceMockRecorder
	isgomock struct{}
}

// MocksublinksServiceMockRecorder is the mock recorder for MocksublinksService.
type MocksublinksServiceMockRecorder struct {
	mock *MocksublinksService
}

// NewMocksublinksService creates a new mock instance.
func NewMocksublinksService(ctrl *gomock.Controller) *MocksublinksService {
	mock := &MocksublinksService{ctrl: ctrl}
	mock.recorder = &MocksublinksServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksublinksService) EXPECT() *MocksublinksServiceMockRecorder {
	return m.recorder
}

// Links mocks base method.
func (m *MocksublinksService) Links(ctx context.Context, users []entity.User) (map[int64][]entity.SubLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Links", ctx, users)
	ret0, _ := ret[0].(map[int64][]entity.SubLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Links indicates an expected call of Links.
func (mr *MocksublinksServiceMockRecorder) Links(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Links", reflect.TypeOf((*MocksublinksService)(nil).Links), ctx, users)
}
