// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package configs
//

// Package configs is a generated GoMock package.
package configs

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockcloner is a mock of cloner interface.
type Mockcloner struct {
	ctrl     *gomock.Controller
	recorder *MockclonerMockRecorder
	isgomock struct{}
}

// MockclonerMockRecorder is the mock recorder for Mockcloner.
type MockclonerMockRecorder struct {
	mock *Mockcloner
}

// NewMockcloner creates a new mock instance.
func NewMockcloner(ctrl *gomock.Controller) *Mockcloner {
	mock := &Mockcloner{ctrl: ctrl}
	mock.recorder = &MockclonerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcloner) EXPECT() *MockclonerMockRecorder {
	return m.recorder
}

// CloneConfig mocks base method.
func (m *Mockcloner) CloneConfig(ctx context.Context, tx *sql.Tx, srcConfigID, dstConfigID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneConfig", ctx, tx, srcConfigID, dstConfigID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloneConfig indicates an expected call of CloneConfig.
func (mr *MockclonerMockRecorder) CloneConfig(ctx, tx, srcConfigID, dstConfigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneConfig", reflect.TypeOf((*Mockcloner)(nil).CloneConfig), ctx, tx, srcConfigID, dstConfigID)
}
