// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package configs
//

// Package configs is a generated GoMock package.
package configs

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockroutingRepo is a mock of routingRepo interface.
type MockroutingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockroutingRepoMockRecorder
	isgomock struct{}
}

// MockroutingRepoMockRecorder is the mock recorder for MockroutingRepo.
type MockroutingRepoMockRecorder struct {
	mock *MockroutingRepo
}

// NewMockroutingRepo creates a new mock instance.
func NewMockroutingRepo(ctrl *gomock.Controller) *MockroutingRepo {
	mock := &MockroutingRepo{ctrl: ctrl}
	mock.recorder = &MockroutingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroutingRepo) EXPECT() *MockroutingRepoMockRecorder {
	return m.recorder
}

// CloneConfig mocks base method.
func (m *MockroutingRepo) CloneConfig(ctx context.Context, tx *sql.Tx, srcConfigID, dstConfigID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneConfig", ctx, tx, srcConfigID, dstConfigID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloneConfig indicates an expected call of CloneConfig.
func (mr *MockroutingRepoMockRecorder) CloneConfig(ctx, tx, srcConfigID, dstConfigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneConfig", reflect.TypeOf((*MockroutingRepo)(nil).CloneConfig), ctx, tx, srcConfigID, dstConfigID)
}
