// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package node_save
//

// Package node_save is a generated GoMock package.
package node_save

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocknodesService is a mock of nodesService interface.
type MocknodesService struct {
	ctrl     *gomock.Controller
	recorder *MocknodesServiceMockRecorder
	isgomock struct{}
}

// MocknodesServiceMockRecorder is the mock recorder for MocknodesService.
type MocknodesServiceMockRecorder struct {
	mock *MocknodesService
}

// NewMocknodesService creates a new mock instance.
func NewMocknodesService(ctrl *gomock.Controller) *MocknodesService {
	mock := &MocknodesService{ctrl: ctrl}
	mock.recorder = &MocknodesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodesService) EXPECT() *MocknodesServiceMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MocknodesService) Save(ctx context.Context, n entity.Node) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, n)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MocknodesServiceMockRecorder) Save(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MocknodesService)(nil).Save), ctx, n)
}
