// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package node_save
//

// Package node_save is a generated GoMock package.
package node_save

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocknodeSaver is a mock of nodeSaver interface.
type MocknodeSaver struct {
	ctrl     *gomock.Controller
	recorder *MocknodeSaverMockRecorder
	isgomock struct{}
}

// MocknodeSaverMockRecorder is the mock recorder for MocknodeSaver.
type MocknodeSaverMockRecorder struct {
	mock *MocknodeSaver
}

// NewMocknodeSaver creates a new mock instance.
func NewMocknodeSaver(ctrl *gomock.Controller) *MocknodeSaver {
	mock := &MocknodeSaver{ctrl: ctrl}
	mock.recorder = &MocknodeSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodeSaver) EXPECT() *MocknodeSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MocknodeSaver) Save(ctx context.Context, n entity.Node) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, n)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MocknodeSaverMockRecorder) Save(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MocknodeSaver)(nil).Save), ctx, n)
}
