// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination contract_mocks.go -package nodes
//

// Package nodes is a generated GoMock package.
package nodes

import (
	context "context"
	reflect "reflect"

	entity "github.com/postlog/subgen/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocknodesRepo is a mock of nodesRepo interface.
type MocknodesRepo struct {
	ctrl     *gomock.Controller
	recorder *MocknodesRepoMockRecorder
	isgomock struct{}
}

// MocknodesRepoMockRecorder is the mock recorder for MocknodesRepo.
type MocknodesRepoMockRecorder struct {
	mock *MocknodesRepo
}

// NewMocknodesRepo creates a new mock instance.
func NewMocknodesRepo(ctrl *gomock.Controller) *MocknodesRepo {
	mock := &MocknodesRepo{ctrl: ctrl}
	mock.recorder = &MocknodesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodesRepo) EXPECT() *MocknodesRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocknodesRepo) Create(ctx context.Context, n entity.Node) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocknodesRepoMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocknodesRepo)(nil).Create), ctx, n)
}

// Delete mocks base method.
func (m *MocknodesRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocknodesRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocknodesRepo)(nil).Delete), ctx, id)
}

// Update mocks base method.
func (m *MocknodesRepo) Update(ctx context.Context, id int64, n entity.Node, setToken bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, n, setToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MocknodesRepoMockRecorder) Update(ctx, id, n, setToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MocknodesRepo)(nil).Update), ctx, id, n, setToken)
}
